// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertDoctorSpecialties implements pgx.CopyFromSource.
type iteratorForInsertDoctorSpecialties struct {
	rows                 []InsertDoctorSpecialtiesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDoctorSpecialties) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDoctorSpecialties) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].DoctorProfileID,
		r.rows[0].SpecialtyID,
	}, nil
}

func (r iteratorForInsertDoctorSpecialties) Err() error {
	return nil
}

func (q *Queries) InsertDoctorSpecialties(ctx context.Context, arg []InsertDoctorSpecialtiesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"doctors_profile_specialties"}, []string{"doctor_profile_id", "specialty_id"}, &iteratorForInsertDoctorSpecialties{rows: arg})
}
