// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const setProfileImageFile = `-- name: SetProfileImageFile :exec
UPDATE identity_users
SET profile_image_file_id = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type SetProfileImageFileParams struct {
	ID                 int64
	ProfileImageFileID *int64
}

func (q *Queries) SetProfileImageFile(ctx context.Context, arg SetProfileImageFileParams) error {
	_, err := q.db.Exec(ctx, setProfileImageFile, arg.ID, arg.ProfileImageFileID)
	return err
}
