// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, role, profile_image_url, created_at
FROM identity_users
WHERE email = $1 AND deleted_at IS NULL
`

type FindUserByEmailRow struct {
	ID              int64
	Email           string
	PasswordHash    string
	Role            UserRole
	ProfileImageUrl pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.ProfileImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
