// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVoteForUpdate = `-- name: GetVoteForUpdate :one
SELECT
    id, action_type, target_user_id, status, required_votes,
    votes_for, votes_against, expires_at, resolved_at, payload,
    xmin::text AS xmin
FROM admin_votes
WHERE id = $1 AND deleted_at IS NULL
`

type GetVoteForUpdateRow struct {
	ID            int64
	ActionType    string
	TargetUserID  int64
	Status        VoteStatus
	RequiredVotes int32
	VotesFor      int32
	VotesAgainst  int32
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	Payload       []byte
	Xmin          string
}

func (q *Queries) GetVoteForUpdate(ctx context.Context, id int64) (GetVoteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVoteForUpdate, id)
	var i GetVoteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.TargetUserID,
		&i.Status,
		&i.RequiredVotes,
		&i.VotesFor,
		&i.VotesAgainst,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.Payload,
		&i.Xmin,
	)
	return i, err
}

const getVoteParticipants = `-- name: GetVoteParticipants :many
SELECT id, admin_vote_id, admin_user_id, vote, voted_at
FROM admin_vote_participants
WHERE admin_vote_id = $1
ORDER BY voted_at
`

func (q *Queries) GetVoteParticipants(ctx context.Context, adminVoteID int64) ([]AdminVoteParticipant, error) {
	rows, err := q.db.Query(ctx, getVoteParticipants, adminVoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminVoteParticipant
	for rows.Next() {
		var i AdminVoteParticipant
		if err := rows.Scan(
			&i.ID,
			&i.AdminVoteID,
			&i.AdminUserID,
			&i.Vote,
			&i.VotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVoteParticipant = `-- name: InsertVoteParticipant :exec
INSERT INTO admin_vote_participants (admin_vote_id, admin_user_id, vote, voted_at)
VALUES ($1, $2, $3, $4)
`

type InsertVoteParticipantParams struct {
	AdminVoteID int64
	AdminUserID int64
	Vote        VoteChoice
	VotedAt     pgtype.Timestamptz
}

func (q *Queries) InsertVoteParticipant(ctx context.Context, arg InsertVoteParticipantParams) error {
	_, err := q.db.Exec(ctx, insertVoteParticipant,
		arg.AdminVoteID,
		arg.AdminUserID,
		arg.Vote,
		arg.VotedAt,
	)
	return err
}

const updateVoteTally = `-- name: UpdateVoteTally :execrows
UPDATE admin_votes
SET votes_for     = $1,
    votes_against = $2,
    status        = $3,
    resolved_at   = $4,
    updated_at    = now()
WHERE id = $5 AND xmin::text = $6
`

type UpdateVoteTallyParams struct {
	VotesFor     int32
	VotesAgainst int32
	Status       VoteStatus
	ResolvedAt   pgtype.Timestamptz
	ID           int64
	Xmin         pgtype.Uint32
}

func (q *Queries) UpdateVoteTally(ctx context.Context, arg UpdateVoteTallyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVoteTally,
		arg.VotesFor,
		arg.VotesAgainst,
		arg.Status,
		arg.ResolvedAt,
		arg.ID,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
