// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blocksForDoctor = `-- name: BlocksForDoctor :many
SELECT day_of_week, start_time, end_time, slot_duration_minutes, is_active
FROM doctors_weekly_schedules
WHERE doctor_profile_id = $1 AND is_active
`

type BlocksForDoctorRow struct {
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) BlocksForDoctor(ctx context.Context, doctorProfileID int64) ([]BlocksForDoctorRow, error) {
	rows, err := q.db.Query(ctx, blocksForDoctor, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlocksForDoctorRow
	for rows.Next() {
		var i BlocksForDoctorRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDurationMinutes,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookedSlots = `-- name: BookedSlots :many
SELECT scheduled_at
FROM consultations_consultations
WHERE doctor_profile_id = $1
  AND scheduled_at >= $2 AND scheduled_at < $3
  AND deleted_at IS NULL
  AND (
    status IN ('Confirmed', 'InProgress')
        OR (status = 'Pending' AND created_at > now() - INTERVAL '15 minutes')
    )
`

type BookedSlotsParams struct {
	DoctorProfileID int64
	FromTs          pgtype.Timestamptz
	ToTs            pgtype.Timestamptz
}

func (q *Queries) BookedSlots(ctx context.Context, arg BookedSlotsParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, bookedSlots, arg.DoctorProfileID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var scheduled_at pgtype.Timestamptz
		if err := rows.Scan(&scheduled_at); err != nil {
			return nil, err
		}
		items = append(items, scheduled_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exceptionsForDoctor = `-- name: ExceptionsForDoctor :many
SELECT exception_date, from_time, to_time, type
FROM doctors_schedule_exceptions
WHERE doctor_profile_id = $1
  AND exception_date BETWEEN $2 AND $3
  AND type = 'Closed'
`

type ExceptionsForDoctorParams struct {
	DoctorProfileID int64
	FromDate        pgtype.Date
	ToDate          pgtype.Date
}

type ExceptionsForDoctorRow struct {
	ExceptionDate pgtype.Date
	FromTime      pgtype.Time
	ToTime        pgtype.Time
	Type          ScheduleExceptionType
}

func (q *Queries) ExceptionsForDoctor(ctx context.Context, arg ExceptionsForDoctorParams) ([]ExceptionsForDoctorRow, error) {
	rows, err := q.db.Query(ctx, exceptionsForDoctor, arg.DoctorProfileID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExceptionsForDoctorRow
	for rows.Next() {
		var i ExceptionsForDoctorRow
		if err := rows.Scan(
			&i.ExceptionDate,
			&i.FromTime,
			&i.ToTime,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT
    d.id, d.full_name, d.bio, d.clinic_name, d.clinic_address,
    d.consultation_fee::text AS consultation_fee,
    d.currency,
    d.average_rating::text   AS average_rating,
    d.rating_count,
    u.profile_image_file_id,
    u.profile_image_url,
    d.medical_license_number,
    d.verification_status
FROM doctors_profiles d
         JOIN identity_users u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE d.id = $1
  AND d.deleted_at IS NULL
  AND d.verification_status = 'Verified'
`

type GetDoctorByIDRow struct {
	ID                   int64
	FullName             string
	Bio                  string
	ClinicName           string
	ClinicAddress        string
	ConsultationFee      string
	Currency             string
	AverageRating        string
	RatingCount          int32
	ProfileImageFileID   pgtype.Int8
	ProfileImageUrl      pgtype.Text
	MedicalLicenseNumber pgtype.Text
	VerificationStatus   VerificationStatus
}

func (q *Queries) GetDoctorByID(ctx context.Context, id int64) (GetDoctorByIDRow, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i GetDoctorByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Bio,
		&i.ClinicName,
		&i.ClinicAddress,
		&i.ConsultationFee,
		&i.Currency,
		&i.AverageRating,
		&i.RatingCount,
		&i.ProfileImageFileID,
		&i.ProfileImageUrl,
		&i.MedicalLicenseNumber,
		&i.VerificationStatus,
	)
	return i, err
}

const recentPosts = `-- name: RecentPosts :many
SELECT id, title, COALESCE(excerpt, '') AS excerpt, type, COALESCE(published_at, created_at) AS published_at
FROM content_posts
WHERE doctor_profile_id = $1
  AND is_published
  AND deleted_at IS NULL
ORDER BY published_at DESC NULLS LAST, id DESC
    LIMIT 5
`

type RecentPostsRow struct {
	ID          int64
	Title       string
	Excerpt     string
	Type        PostType
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) RecentPosts(ctx context.Context, doctorProfileID int64) ([]RecentPostsRow, error) {
	rows, err := q.db.Query(ctx, recentPosts, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentPostsRow
	for rows.Next() {
		var i RecentPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Type,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specialtiesForDoctor = `-- name: SpecialtiesForDoctor :many
SELECT s.id, s.name
FROM doctors_profile_specialties dps
         JOIN doctors_specialties s ON s.id = dps.specialty_id
WHERE dps.doctor_profile_id = $1
ORDER BY s.name
`

type SpecialtiesForDoctorRow struct {
	ID   int64
	Name string
}

func (q *Queries) SpecialtiesForDoctor(ctx context.Context, doctorProfileID int64) ([]SpecialtiesForDoctorRow, error) {
	rows, err := q.db.Query(ctx, specialtiesForDoctor, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecialtiesForDoctorRow
	for rows.Next() {
		var i SpecialtiesForDoctorRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
