// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecordForAttachment = `-- name: GetRecordForAttachment :one
SELECT id, doctor_profile_id FROM clinical_medical_records
WHERE consultation_id = $1 AND deleted_at IS NULL
`

type GetRecordForAttachmentRow struct {
	ID              int64
	DoctorProfileID int64
}

func (q *Queries) GetRecordForAttachment(ctx context.Context, consultationID int64) (GetRecordForAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getRecordForAttachment, consultationID)
	var i GetRecordForAttachmentRow
	err := row.Scan(&i.ID, &i.DoctorProfileID)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO clinical_medical_attachments (medical_record_id, file_id, label)
VALUES ($1, $2, $3)
    RETURNING id, created_at
`

type InsertAttachmentParams struct {
	MedicalRecordID int64
	FileID          int64
	Label           *string
}

type InsertAttachmentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (InsertAttachmentRow, error) {
	row := q.db.QueryRow(ctx, insertAttachment, arg.MedicalRecordID, arg.FileID, arg.Label)
	var i InsertAttachmentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
