// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSuspensions = `-- name: CountSuspensions :one
SELECT COUNT(*)::bigint
FROM admin_user_suspensions s
WHERE ($1::boolean IS NULL
       OR $1::boolean = false
       OR (s.lifted_at IS NULL AND (s.to_ts IS NULL OR s.to_ts > now())))
`

func (q *Queries) CountSuspensions(ctx context.Context, activeOnly *bool) (int64, error) {
	row := q.db.QueryRow(ctx, countSuspensions, activeOnly)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listSuspensions = `-- name: ListSuspensions :many
SELECT
    s.id, s.user_id, s.reason, s.from_ts, s.to_ts,
    s.lifted_at, s.lifted_by, s.lift_reason, s.created_at,
    u.email AS user_email,
    u.role  AS user_role
FROM admin_user_suspensions s
JOIN identity_users u ON u.id = s.user_id
WHERE ($3::boolean IS NULL
       OR $3::boolean = false
       OR (s.lifted_at IS NULL AND (s.to_ts IS NULL OR s.to_ts > now())))
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuspensionsParams struct {
	Limit      int32
	Offset     int32
	ActiveOnly *bool
}

type ListSuspensionsRow struct {
	ID         int64
	UserID     int64
	Reason     string
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
	LiftedAt   pgtype.Timestamptz
	LiftedBy   *int64
	LiftReason *string
	CreatedAt  pgtype.Timestamptz
	UserEmail  string
	UserRole   UserRole
}

func (q *Queries) ListSuspensions(ctx context.Context, arg ListSuspensionsParams) ([]ListSuspensionsRow, error) {
	rows, err := q.db.Query(ctx, listSuspensions, arg.Limit, arg.Offset, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuspensionsRow
	for rows.Next() {
		var i ListSuspensionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reason,
			&i.FromTs,
			&i.ToTs,
			&i.LiftedAt,
			&i.LiftedBy,
			&i.LiftReason,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
