// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDoctorProfileID = `-- name: GetDoctorProfileID :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorProfileID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT day_of_week, start_time, end_time, slot_duration_minutes, is_active
FROM doctors_weekly_schedules
WHERE doctor_profile_id = $1
ORDER BY day_of_week, start_time
`

type ListBlocksRow struct {
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) ListBlocks(ctx context.Context, doctorProfileID int64) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlocksRow
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDurationMinutes,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptions = `-- name: ListExceptions :many
SELECT id, exception_date, from_time, to_time, type, reason
FROM doctors_schedule_exceptions
WHERE doctor_profile_id = $1
ORDER BY exception_date, from_time
`

type ListExceptionsRow struct {
	ID            int64
	ExceptionDate pgtype.Date
	FromTime      pgtype.Time
	ToTime        pgtype.Time
	Type          ScheduleExceptionType
	Reason        pgtype.Text
}

func (q *Queries) ListExceptions(ctx context.Context, doctorProfileID int64) ([]ListExceptionsRow, error) {
	rows, err := q.db.Query(ctx, listExceptions, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExceptionsRow
	for rows.Next() {
		var i ListExceptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExceptionDate,
			&i.FromTime,
			&i.ToTime,
			&i.Type,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
