// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPost = `-- name: InsertPost :one
INSERT INTO content_posts (
    doctor_profile_id, title, content, excerpt, type, cover_image_url
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertPostParams struct {
	DoctorProfileID int64
	Title           string
	Content         string
	Excerpt         pgtype.Text
	Type            PostType
	CoverImageUrl   pgtype.Text
}

type InsertPostRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (InsertPostRow, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.DoctorProfileID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Type,
		arg.CoverImageUrl,
	)
	var i InsertPostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
