// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPost = `-- name: InsertPost :one
INSERT INTO content_posts (
    doctor_profile_id, title, content, excerpt, type, cover_image_url, is_published
) VALUES (
             $1, $2, $3, $4, $5, $6, false
         ) RETURNING id, created_at
`

type InsertPostParams struct {
	DoctorProfileID int64
	Title           string
	Content         string
	Excerpt         pgtype.Text
	Type            PostType
	CoverImageUrl   pgtype.Text
}

type InsertPostRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (InsertPostRow, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.DoctorProfileID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Type,
		arg.CoverImageUrl,
	)
	var i InsertPostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPostAttachment = `-- name: InsertPostAttachment :exec
INSERT INTO content_post_attachments (doctor_post_id, file_id)
VALUES ($1, $2)
`

type InsertPostAttachmentParams struct {
	DoctorPostID int64
	FileID       pgtype.Int8
}

func (q *Queries) InsertPostAttachment(ctx context.Context, arg InsertPostAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertPostAttachment, arg.DoctorPostID, arg.FileID)
	return err
}
