// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOpenVote = `-- name: FindOpenVote :one
SELECT id FROM admin_votes
WHERE action_type = $1
  AND target_user_id = $2
  AND status = 'Open'
  AND deleted_at IS NULL
`

type FindOpenVoteParams struct {
	ActionType   string
	TargetUserID int64
}

func (q *Queries) FindOpenVote(ctx context.Context, arg FindOpenVoteParams) (int64, error) {
	row := q.db.QueryRow(ctx, findOpenVote, arg.ActionType, arg.TargetUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserRoleForVote = `-- name: FindUserRoleForVote :one
SELECT role FROM identity_users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserRoleForVote(ctx context.Context, id int64) (UserRole, error) {
	row := q.db.QueryRow(ctx, findUserRoleForVote, id)
	var role UserRole
	err := row.Scan(&role)
	return role, err
}

const insertAdminVote = `-- name: InsertAdminVote :one
INSERT INTO admin_votes (
    action_type, target_user_id, status, required_votes,
    votes_for, votes_against, expires_at, resolved_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, created_at
`

type InsertAdminVoteParams struct {
	ActionType    string
	TargetUserID  int64
	Status        VoteStatus
	RequiredVotes int32
	VotesFor      int32
	VotesAgainst  int32
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
}

type InsertAdminVoteRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertAdminVote(ctx context.Context, arg InsertAdminVoteParams) (InsertAdminVoteRow, error) {
	row := q.db.QueryRow(ctx, insertAdminVote,
		arg.ActionType,
		arg.TargetUserID,
		arg.Status,
		arg.RequiredVotes,
		arg.VotesFor,
		arg.VotesAgainst,
		arg.ExpiresAt,
		arg.ResolvedAt,
	)
	var i InsertAdminVoteRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertVoteParticipant = `-- name: InsertVoteParticipant :exec
INSERT INTO admin_vote_participants (admin_vote_id, admin_user_id, vote, voted_at)
VALUES ($1, $2, $3, $4)
`

type InsertVoteParticipantParams struct {
	AdminVoteID int64
	AdminUserID int64
	Vote        VoteChoice
	VotedAt     pgtype.Timestamptz
}

func (q *Queries) InsertVoteParticipant(ctx context.Context, arg InsertVoteParticipantParams) error {
	_, err := q.db.Exec(ctx, insertVoteParticipant,
		arg.AdminVoteID,
		arg.AdminUserID,
		arg.Vote,
		arg.VotedAt,
	)
	return err
}

const resolveVoteImmediately = `-- name: ResolveVoteImmediately :execrows
UPDATE admin_votes
SET status = 'Resolved', resolved_at = $2, updated_at = now()
WHERE id = $1 AND status = 'Open' AND xmin::text = $3
`

type ResolveVoteImmediatelyParams struct {
	ID         int64
	ResolvedAt pgtype.Timestamptz
	Xmin       pgtype.Uint32
}

func (q *Queries) ResolveVoteImmediately(ctx context.Context, arg ResolveVoteImmediatelyParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveVoteImmediately, arg.ID, arg.ResolvedAt, arg.Xmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
