// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::bigint
FROM identity_users
WHERE ($1::text IS NULL OR role::text = $1)
  AND ($2::text IS NULL
       OR email ILIKE '%' || $2 || '%')
  AND deleted_at IS NULL
`

type CountUsersParams struct {
	Role   *string
	Search *string
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Role, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, role, email_verified_at, created_at, deleted_at
FROM identity_users
WHERE ($3::text IS NULL OR role::text = $3)
  AND ($4::text IS NULL
       OR email ILIKE '%' || $4 || '%')
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
	Role   *string
	Search *string
}

type ListUsersRow struct {
	ID              int64
	Email           string
	Role            UserRole
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Role,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
