// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const isQueueMember = `-- name: IsQueueMember :one
SELECT EXISTS (
    SELECT 1 FROM doctors_clinic_sessions s
    JOIN doctors_profiles d ON d.id = s.doctor_profile_id
    JOIN identity_users u ON u.id = d.user_id
    WHERE s.id = $1 AND u.id = $2
    UNION ALL
    SELECT 1 FROM queue_entries qe
    JOIN patients_profiles p ON p.id = qe.patient_profile_id
    WHERE qe.clinic_session_id = $1
      AND p.user_id = $2
      AND qe.status NOT IN ('Completed', 'NoShow', 'Cancelled')
    UNION ALL
    SELECT 1 FROM identity_users
    WHERE id = $2 AND role = 'Admin'
) AS is_member
`

type IsQueueMemberParams struct {
	ClinicSessionID int64
	UserID          int64
}

// Doctor of the session, admin, or a patient with a non-terminal entry.
func (q *Queries) IsQueueMember(ctx context.Context, arg IsQueueMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isQueueMember, arg.ClinicSessionID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
