// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const deleteException = `-- name: DeleteException :execrows
DELETE FROM doctors_schedule_exceptions e
USING doctors_profiles p
WHERE e.id = $1
  AND e.doctor_profile_id = p.id
  AND p.user_id = $2
  AND p.deleted_at IS NULL
`

type DeleteExceptionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteException(ctx context.Context, arg DeleteExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteException, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
