// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	file "tibi/internal/files"
)

const insertFile = `-- name: InsertFile :one
INSERT INTO platform_files (
    uploader_id, scope, object_key, original_name,
    content_type, size_bytes, content_sha256
) VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, created_at
`

type InsertFileParams struct {
	UploaderID    int64
	Scope         file.Scope
	ObjectKey     string
	OriginalName  string
	ContentType   string
	SizeBytes     int64
	ContentSha256 string
}

type InsertFileRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (InsertFileRow, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.UploaderID,
		arg.Scope,
		arg.ObjectKey,
		arg.OriginalName,
		arg.ContentType,
		arg.SizeBytes,
		arg.ContentSha256,
	)
	var i InsertFileRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
