// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*)::bigint
FROM communication_messages m
JOIN consultations_consultations c ON c.id = m.consultation_id
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles  d ON d.id = c.doctor_profile_id
WHERE m.consultation_id = $1
  AND m.deleted_at IS NULL
  AND (p.user_id = $2 OR d.user_id = $2)
`

type CountMessagesParams struct {
	ConsultationID int64
	UserID         int64
}

func (q *Queries) CountMessages(ctx context.Context, arg CountMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, arg.ConsultationID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id, m.consultation_id, m.sender_user_id, m.content,
    m.sent_at, m.read_at
FROM communication_messages m
JOIN consultations_consultations c ON c.id = m.consultation_id
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles  d ON d.id = c.doctor_profile_id
WHERE m.consultation_id = $1
  AND m.deleted_at IS NULL
  AND (p.user_id = $2 OR d.user_id = $2)
ORDER BY m.sent_at DESC, m.id DESC
LIMIT $3 OFFSET $4
`

type ListMessagesParams struct {
	ConsultationID int64
	UserID         int64
	Limit          int32
	Offset         int32
}

type ListMessagesRow struct {
	ID             int64
	ConsultationID int64
	SenderUserID   int64
	Content        string
	SentAt         pgtype.Timestamptz
	ReadAt         pgtype.Timestamptz
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConsultationID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.SenderUserID,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :exec
UPDATE communication_messages
SET read_at = now()
WHERE consultation_id = $1
  AND sender_user_id != $2
  AND read_at IS NULL
  AND deleted_at IS NULL
`

type MarkMessagesReadParams struct {
	ConsultationID int64
	SenderUserID   int64
}

func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesRead, arg.ConsultationID, arg.SenderUserID)
	return err
}
