// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPendingPayment = `-- name: InsertPendingPayment :one
INSERT INTO payments_payments (
    patient_profile_id, doctor_profile_id, consultation_id,
    amount, currency, channel, checkout_url
) VALUES (
             $1,
             $2,
             $3,
             $4::numeric,       -- Named parameter with cast
             $5,
             $6,
             $7
         )
    RETURNING id, created_at
`

type InsertPendingPaymentParams struct {
	PatientProfileID int64
	DoctorProfileID  int64
	ConsultationID   int64
	Amount           pgtype.Numeric
	Currency         string
	Channel          PaymentChannel
	CheckoutUrl      pgtype.Text
}

type InsertPendingPaymentRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPendingPayment(ctx context.Context, arg InsertPendingPaymentParams) (InsertPendingPaymentRow, error) {
	row := q.db.QueryRow(ctx, insertPendingPayment,
		arg.PatientProfileID,
		arg.DoctorProfileID,
		arg.ConsultationID,
		arg.Amount,
		arg.Currency,
		arg.Channel,
		arg.CheckoutUrl,
	)
	var i InsertPendingPaymentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
