// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmailForReset = `-- name: GetUserByEmailForReset :one
SELECT id, email FROM identity_users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailForResetRow struct {
	ID    int64
	Email string
}

func (q *Queries) GetUserByEmailForReset(ctx context.Context, email string) (GetUserByEmailForResetRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForReset, email)
	var i GetUserByEmailForResetRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const insertPasswordReset = `-- name: InsertPasswordReset :exec
INSERT INTO identity_password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertPasswordResetParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) error {
	_, err := q.db.Exec(ctx, insertPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const invalidateOpenPasswordResets = `-- name: InvalidateOpenPasswordResets :exec
UPDATE identity_password_resets
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateOpenPasswordResets(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateOpenPasswordResets, userID)
	return err
}
