// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSuspensionTarget = `-- name: GetSuspensionTarget :one
SELECT u.id AS user_id, u.role
FROM identity_users u
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetSuspensionTargetRow struct {
	UserID int64
	Role   UserRole
}

func (q *Queries) GetSuspensionTarget(ctx context.Context, id int64) (GetSuspensionTargetRow, error) {
	row := q.db.QueryRow(ctx, getSuspensionTarget, id)
	var i GetSuspensionTargetRow
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}

const hasActiveSuspension = `-- name: HasActiveSuspension :one
SELECT EXISTS (
    SELECT 1 FROM admin_user_suspensions
    WHERE user_id = $1
      AND lifted_at IS NULL
      AND (to_ts IS NULL OR to_ts > now())
) AS has_active
`

func (q *Queries) HasActiveSuspension(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSuspension, userID)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const insertSuspensionVote = `-- name: InsertSuspensionVote :one
INSERT INTO admin_votes (
    action_type, target_user_id, status,
    required_votes, votes_for, votes_against, expires_at, payload
) VALUES ('BanUser', $1, 'Open', $2, 1, 0, $3, $4)
RETURNING id, created_at
`

type InsertSuspensionVoteParams struct {
	TargetUserID  int64
	RequiredVotes int32
	ExpiresAt     pgtype.Timestamptz
	Payload       []byte
}

type InsertSuspensionVoteRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSuspensionVote(ctx context.Context, arg InsertSuspensionVoteParams) (InsertSuspensionVoteRow, error) {
	row := q.db.QueryRow(ctx, insertSuspensionVote,
		arg.TargetUserID,
		arg.RequiredVotes,
		arg.ExpiresAt,
		arg.Payload,
	)
	var i InsertSuspensionVoteRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertSuspensionVoteParticipant = `-- name: InsertSuspensionVoteParticipant :exec
INSERT INTO admin_vote_participants (admin_vote_id, admin_user_id, vote, voted_at)
VALUES ($1, $2, 'For', $3)
`

type InsertSuspensionVoteParticipantParams struct {
	AdminVoteID int64
	AdminUserID int64
	VotedAt     pgtype.Timestamptz
}

func (q *Queries) InsertSuspensionVoteParticipant(ctx context.Context, arg InsertSuspensionVoteParticipantParams) error {
	_, err := q.db.Exec(ctx, insertSuspensionVoteParticipant, arg.AdminVoteID, arg.AdminUserID, arg.VotedAt)
	return err
}
