// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getConsultationForCheckIn = `-- name: GetConsultationForCheckIn :one

SELECT
    c.id, c.patient_profile_id, c.doctor_profile_id,
    c.clinic_session_id, c.duration_minutes, c.is_urgent, c.status
FROM consultations_consultations c
JOIN patients_profiles p ON p.id = c.patient_profile_id
WHERE c.id = $1
  AND p.user_id = $2
  AND c.status = 'Confirmed'
  AND c.deleted_at IS NULL
`

type GetConsultationForCheckInParams struct {
	ID     int64
	UserID int64
}

type GetConsultationForCheckInRow struct {
	ID               int64
	PatientProfileID int64
	DoctorProfileID  int64
	ClinicSessionID  *int64
	DurationMinutes  int32
	IsUrgent         bool
	Status           ConsultationStatus
}

// Cross-module read: joins consultations_consultations (Consultations)
// with patients_profiles (Patients). Permitted by R2.
func (q *Queries) GetConsultationForCheckIn(ctx context.Context, arg GetConsultationForCheckInParams) (GetConsultationForCheckInRow, error) {
	row := q.db.QueryRow(ctx, getConsultationForCheckIn, arg.ID, arg.UserID)
	var i GetConsultationForCheckInRow
	err := row.Scan(
		&i.ID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.ClinicSessionID,
		&i.DurationMinutes,
		&i.IsUrgent,
		&i.Status,
	)
	return i, err
}
