// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserForVerification = `-- name: GetUserForVerification :one
SELECT id, email, email_verified_at
FROM identity_users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserForVerificationRow struct {
	ID              int64
	Email           string
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetUserForVerification(ctx context.Context, id int64) (GetUserForVerificationRow, error) {
	row := q.db.QueryRow(ctx, getUserForVerification, id)
	var i GetUserForVerificationRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerifiedAt)
	return i, err
}

const insertEmailVerification = `-- name: InsertEmailVerification :exec
INSERT INTO identity_email_verifications (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type InsertEmailVerificationParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertEmailVerification(ctx context.Context, arg InsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerification, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const invalidateOpenVerifications = `-- name: InvalidateOpenVerifications :exec
UPDATE identity_email_verifications
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

func (q *Queries) InvalidateOpenVerifications(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateOpenVerifications, userID)
	return err
}
