// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecordByConsultation = `-- name: GetRecordByConsultation :one
SELECT id, consultation_id, patient_profile_id, doctor_profile_id,
       allergies, current_medications, past_conditions, doctor_notes,
       created_at, updated_at, deleted_at,
       xmin::text AS xmin
FROM clinical_medical_records
WHERE consultation_id = $1 AND deleted_at IS NULL
`

type GetRecordByConsultationRow struct {
	ID                 int64
	ConsultationID     int64
	PatientProfileID   int64
	DoctorProfileID    int64
	Allergies          *string
	CurrentMedications *string
	PastConditions     *string
	DoctorNotes        *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Xmin               string
}

func (q *Queries) GetRecordByConsultation(ctx context.Context, consultationID int64) (GetRecordByConsultationRow, error) {
	row := q.db.QueryRow(ctx, getRecordByConsultation, consultationID)
	var i GetRecordByConsultationRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.Allergies,
		&i.CurrentMedications,
		&i.PastConditions,
		&i.DoctorNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Xmin,
	)
	return i, err
}

const insertRecord = `-- name: InsertRecord :one
INSERT INTO clinical_medical_records (
    consultation_id, patient_profile_id, doctor_profile_id,
    allergies, current_medications, past_conditions, doctor_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, created_at, updated_at, xmin::text AS xmin
`

type InsertRecordParams struct {
	ConsultationID     int64
	PatientProfileID   int64
	DoctorProfileID    int64
	Allergies          *string
	CurrentMedications *string
	PastConditions     *string
	DoctorNotes        *string
}

type InsertRecordRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Xmin      string
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) (InsertRecordRow, error) {
	row := q.db.QueryRow(ctx, insertRecord,
		arg.ConsultationID,
		arg.PatientProfileID,
		arg.DoctorProfileID,
		arg.Allergies,
		arg.CurrentMedications,
		arg.PastConditions,
		arg.DoctorNotes,
	)
	var i InsertRecordRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xmin,
	)
	return i, err
}

const updateRecord = `-- name: UpdateRecord :execrows
UPDATE clinical_medical_records
SET allergies = $2, current_medications = $3,
    past_conditions = $4, doctor_notes = $5,
    updated_at = $6
WHERE id = $1 AND xmin::text = $7
`

type UpdateRecordParams struct {
	ID                 int64
	Allergies          *string
	CurrentMedications *string
	PastConditions     *string
	DoctorNotes        *string
	UpdatedAt          pgtype.Timestamptz
	Xmin               pgtype.Uint32
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRecord,
		arg.ID,
		arg.Allergies,
		arg.CurrentMedications,
		arg.PastConditions,
		arg.DoctorNotes,
		arg.UpdatedAt,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
