// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClosedException = `-- name: GetClosedException :one
SELECT id FROM doctors_schedule_exceptions
WHERE doctor_profile_id = $1
  AND exception_date = $2
  AND from_time <= $3::time
  AND to_time >= $4::time
  AND type = 'Closed'
LIMIT 1
`

type GetClosedExceptionParams struct {
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
	FromTime        pgtype.Time
	ToTime          pgtype.Time
}

func (q *Queries) GetClosedException(ctx context.Context, arg GetClosedExceptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getClosedException,
		arg.DoctorProfileID,
		arg.ExceptionDate,
		arg.FromTime,
		arg.ToTime,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDoctorBlockForDate = `-- name: GetDoctorBlockForDate :one
SELECT start_time, end_time, slot_duration_minutes
FROM doctors_weekly_schedules
WHERE doctor_profile_id = $1
  AND day_of_week = EXTRACT(DOW FROM $2::date)
  AND is_active
  AND start_time <= $3::time
  AND end_time >= $4::time
LIMIT 1
`

type GetDoctorBlockForDateParams struct {
	DoctorProfileID int64
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
}

type GetDoctorBlockForDateRow struct {
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
}

func (q *Queries) GetDoctorBlockForDate(ctx context.Context, arg GetDoctorBlockForDateParams) (GetDoctorBlockForDateRow, error) {
	row := q.db.QueryRow(ctx, getDoctorBlockForDate,
		arg.DoctorProfileID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var i GetDoctorBlockForDateRow
	err := row.Scan(&i.StartTime, &i.EndTime, &i.SlotDurationMinutes)
	return i, err
}

const getDoctorProfileByID = `-- name: GetDoctorProfileByID :one
SELECT id, verification_status
FROM doctors_profiles
WHERE id = $1 AND deleted_at IS NULL
`

type GetDoctorProfileByIDRow struct {
	ID                 int64
	VerificationStatus VerificationStatus
}

func (q *Queries) GetDoctorProfileByID(ctx context.Context, id int64) (GetDoctorProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileByID, id)
	var i GetDoctorProfileByIDRow
	err := row.Scan(&i.ID, &i.VerificationStatus)
	return i, err
}

const getOrCreateSession = `-- name: GetOrCreateSession :one
INSERT INTO doctors_clinic_sessions (
    doctor_profile_id, session_date, start_time, end_time
) VALUES (
             $1, $2, $3::time, $4::time
         )
    ON CONFLICT (doctor_profile_id, session_date, start_time)
DO UPDATE SET end_time = doctors_clinic_sessions.end_time
           RETURNING id, created_at
`

type GetOrCreateSessionParams struct {
	DoctorProfileID int64
	SessionDate     pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
}

type GetOrCreateSessionRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetOrCreateSession(ctx context.Context, arg GetOrCreateSessionParams) (GetOrCreateSessionRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateSession,
		arg.DoctorProfileID,
		arg.SessionDate,
		arg.StartTime,
		arg.EndTime,
	)
	var i GetOrCreateSessionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
