// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const unreadCount = `-- name: UnreadCount :one
SELECT COUNT(*)::bigint
FROM communication_notifications
WHERE user_id = $1 AND is_read = false AND deleted_at IS NULL
`

func (q *Queries) UnreadCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, unreadCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
