// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const profileID = `-- name: ProfileID :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ProfileID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, profileID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE content_posts SET
    title = COALESCE($1, title),
    content = COALESCE($2, content),
    excerpt = COALESCE($3, excerpt),
    type = COALESCE($4::post_type, type),
    cover_image_url = COALESCE($5, cover_image_url),
    updated_at = now()
WHERE id = $6
  AND doctor_profile_id = $7
  AND deleted_at IS NULL
RETURNING id, updated_at
`

type UpdatePostParams struct {
	Title           pgtype.Text
	Content         pgtype.Text
	Excerpt         pgtype.Text
	Type            NullPostType
	CoverImageUrl   pgtype.Text
	ID              int64
	DoctorProfileID int64
}

type UpdatePostRow struct {
	ID        int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.Type,
		arg.CoverImageUrl,
		arg.ID,
		arg.DoctorProfileID,
	)
	var i UpdatePostRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}
