// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getByID = `-- name: GetByID :one
SELECT c.id, c.status, c.scheduled_at, c.duration_minutes, c.is_urgent, c.notes,
       c.doctor_profile_id, d.full_name AS doctor_name,
       c.patient_profile_id, p.full_name AS patient_name,
       p.user_id AS patient_user_id, d.user_id AS doctor_user_id, c.created_at
FROM consultations_consultations c
JOIN doctors_profiles d ON d.id = c.doctor_profile_id
JOIN patients_profiles p ON p.id = c.patient_profile_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetByIDRow struct {
	ID               int64
	Status           ConsultationStatus
	ScheduledAt      pgtype.Timestamptz
	DurationMinutes  int32
	IsUrgent         bool
	Notes            pgtype.Text
	DoctorProfileID  int64
	DoctorName       string
	PatientProfileID int64
	PatientName      string
	PatientUserID    int64
	DoctorUserID     int64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetByID(ctx context.Context, id int64) (GetByIDRow, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i GetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ScheduledAt,
		&i.DurationMinutes,
		&i.IsUrgent,
		&i.Notes,
		&i.DoctorProfileID,
		&i.DoctorName,
		&i.PatientProfileID,
		&i.PatientName,
		&i.PatientUserID,
		&i.DoctorUserID,
		&i.CreatedAt,
	)
	return i, err
}
