// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isPublished = `-- name: IsPublished :one
SELECT is_published FROM content_posts
WHERE id = $1 AND doctor_profile_id = $2 AND deleted_at IS NULL
`

type IsPublishedParams struct {
	ID              int64
	DoctorProfileID int64
}

func (q *Queries) IsPublished(ctx context.Context, arg IsPublishedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPublished, arg.ID, arg.DoctorProfileID)
	var is_published bool
	err := row.Scan(&is_published)
	return is_published, err
}

const profileID = `-- name: ProfileID :one
SELECT id FROM doctors_profiles WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ProfileID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, profileID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const publish = `-- name: Publish :execrows
UPDATE content_posts
SET is_published = true, published_at = $3, updated_at = $3
WHERE id = $1 AND doctor_profile_id = $2 AND deleted_at IS NULL AND is_published = false
`

type PublishParams struct {
	ID              int64
	DoctorProfileID int64
	PublishedAt     pgtype.Timestamptz
}

func (q *Queries) Publish(ctx context.Context, arg PublishParams) (int64, error) {
	result, err := q.db.Exec(ctx, publish, arg.ID, arg.DoctorProfileID, arg.PublishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
