// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const averageCompletedSeconds = `-- name: AverageCompletedSeconds :one
SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (completed_at - started_at))), 0)::float8 AS avg_seconds
FROM queue_entries
WHERE queue_window_id = $1
  AND status = 'Completed'
  AND started_at IS NOT NULL
  AND completed_at IS NOT NULL
`

func (q *Queries) AverageCompletedSeconds(ctx context.Context, queueWindowID int64) (float64, error) {
	row := q.db.QueryRow(ctx, averageCompletedSeconds, queueWindowID)
	var avg_seconds float64
	err := row.Scan(&avg_seconds)
	return avg_seconds, err
}
