// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listForUser = `-- name: ListForUser :many
SELECT c.id, c.status, c.scheduled_at, c.duration_minutes, c.is_urgent,
       c.doctor_profile_id, d.full_name AS doctor_name,
       c.patient_profile_id, p.full_name AS patient_name
FROM consultations_consultations c
JOIN doctors_profiles d ON d.id = c.doctor_profile_id
JOIN patients_profiles p ON p.id = c.patient_profile_id
WHERE c.deleted_at IS NULL
  AND (p.user_id = $1 OR d.user_id = $1)
ORDER BY c.scheduled_at DESC
LIMIT 100
`

type ListForUserRow struct {
	ID               int64
	Status           ConsultationStatus
	ScheduledAt      pgtype.Timestamptz
	DurationMinutes  int32
	IsUrgent         bool
	DoctorProfileID  int64
	DoctorName       string
	PatientProfileID int64
	PatientName      string
}

func (q *Queries) ListForUser(ctx context.Context, userID int64) ([]ListForUserRow, error) {
	rows, err := q.db.Query(ctx, listForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForUserRow
	for rows.Next() {
		var i ListForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ScheduledAt,
			&i.DurationMinutes,
			&i.IsUrgent,
			&i.DoctorProfileID,
			&i.DoctorName,
			&i.PatientProfileID,
			&i.PatientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
