// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blocksForDoctor = `-- name: BlocksForDoctor :many
SELECT day_of_week, start_time, end_time, slot_duration_minutes, is_active
FROM doctors_weekly_schedules
WHERE doctor_profile_id = $1 AND is_active
`

type BlocksForDoctorRow struct {
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) BlocksForDoctor(ctx context.Context, doctorProfileID int64) ([]BlocksForDoctorRow, error) {
	rows, err := q.db.Query(ctx, blocksForDoctor, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlocksForDoctorRow
	for rows.Next() {
		var i BlocksForDoctorRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDurationMinutes,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookedOnDate = `-- name: BookedOnDate :many
SELECT scheduled_at
FROM consultations_consultations
WHERE doctor_profile_id = $1
  AND scheduled_at >= $2 AND scheduled_at < $3
  AND deleted_at IS NULL
  AND (
    status IN ('Confirmed', 'InProgress')
        OR (status = 'Pending' AND created_at > now() - INTERVAL '15 minutes')
    )
`

type BookedOnDateParams struct {
	DoctorProfileID int64
	FromTs          pgtype.Timestamptz
	ToTs            pgtype.Timestamptz
}

func (q *Queries) BookedOnDate(ctx context.Context, arg BookedOnDateParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, bookedOnDate, arg.DoctorProfileID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var scheduled_at pgtype.Timestamptz
		if err := rows.Scan(&scheduled_at); err != nil {
			return nil, err
		}
		items = append(items, scheduled_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exceptionsOnDate = `-- name: ExceptionsOnDate :many
SELECT exception_date, from_time, to_time, type
FROM doctors_schedule_exceptions
WHERE doctor_profile_id = $1
  AND exception_date = $2
  AND type = 'Closed'
`

type ExceptionsOnDateParams struct {
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
}

type ExceptionsOnDateRow struct {
	ExceptionDate pgtype.Date
	FromTime      pgtype.Time
	ToTime        pgtype.Time
	Type          ScheduleExceptionType
}

func (q *Queries) ExceptionsOnDate(ctx context.Context, arg ExceptionsOnDateParams) ([]ExceptionsOnDateRow, error) {
	rows, err := q.db.Query(ctx, exceptionsOnDate, arg.DoctorProfileID, arg.ExceptionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExceptionsOnDateRow
	for rows.Next() {
		var i ExceptionsOnDateRow
		if err := rows.Scan(
			&i.ExceptionDate,
			&i.FromTime,
			&i.ToTime,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerifiedDoctor = `-- name: GetVerifiedDoctor :one
SELECT id FROM doctors_profiles
WHERE id = $1 AND verification_status = 'Verified' AND deleted_at IS NULL
`

func (q *Queries) GetVerifiedDoctor(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getVerifiedDoctor, id)
	err := row.Scan(&id)
	return id, err
}
