// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const isConsultationMember = `-- name: IsConsultationMember :one

SELECT EXISTS (
    SELECT 1 FROM consultations_consultations c
    LEFT JOIN patients_profiles p ON p.id = c.patient_profile_id AND p.user_id = $2
    LEFT JOIN doctors_profiles  d ON d.id = c.doctor_profile_id  AND d.user_id = $2
    WHERE c.id = $1
      AND c.deleted_at IS NULL
      AND (p.id IS NOT NULL OR d.id IS NOT NULL)
) AS is_member
`

type IsConsultationMemberParams struct {
	ID     int64
	UserID int64
}

// Cross-module read: joins consultations_consultations (Consultations)
// with patients_profiles (Patients) and doctors_profiles (Doctors).
// Permitted by R2. Membership rule for WebSocket subscriptions.
func (q *Queries) IsConsultationMember(ctx context.Context, arg IsConsultationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConsultationMember, arg.ID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const otherConsultationMember = `-- name: OtherConsultationMember :one
SELECT
    CASE
        WHEN p.user_id = $2 THEN d.user_id
        ELSE p.user_id
    END::bigint AS other_user_id
FROM consultations_consultations c
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles  d ON d.id = c.doctor_profile_id
WHERE c.id = $1
  AND (p.user_id = $2 OR d.user_id = $2)
`

type OtherConsultationMemberParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) OtherConsultationMember(ctx context.Context, arg OtherConsultationMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, otherConsultationMember, arg.ID, arg.UserID)
	var other_user_id int64
	err := row.Scan(&other_user_id)
	return other_user_id, err
}
