// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPrescriptionForRead = `-- name: GetPrescriptionForRead :one
SELECT r.id, r.consultation_id, r.issued_at, r.created_at, r.updated_at
FROM clinical_prescriptions r
         JOIN consultations_consultations c ON c.id = r.consultation_id
         LEFT JOIN patients_profiles p ON p.id = c.patient_profile_id AND p.user_id = $2
         LEFT JOIN doctors_profiles  d ON d.id = c.doctor_profile_id  AND d.user_id = $2
WHERE r.consultation_id = $1
  AND r.deleted_at IS NULL
  AND (p.id IS NOT NULL OR d.id IS NOT NULL)
`

type GetPrescriptionForReadParams struct {
	ConsultationID int64
	UserID         int64
}

type GetPrescriptionForReadRow struct {
	ID             int64
	ConsultationID int64
	IssuedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetPrescriptionForRead(ctx context.Context, arg GetPrescriptionForReadParams) (GetPrescriptionForReadRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionForRead, arg.ConsultationID, arg.UserID)
	var i GetPrescriptionForReadRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedications = `-- name: ListMedications :many
SELECT id, medication_name, dosage, frequency, duration_days, notes
FROM clinical_prescribed_medications
WHERE prescription_id = $1 AND deleted_at IS NULL
ORDER BY id ASC
`

type ListMedicationsRow struct {
	ID             int64
	MedicationName string
	Dosage         string
	Frequency      string
	DurationDays   int32
	Notes          *string
}

func (q *Queries) ListMedications(ctx context.Context, prescriptionID int64) ([]ListMedicationsRow, error) {
	rows, err := q.db.Query(ctx, listMedications, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMedicationsRow
	for rows.Next() {
		var i ListMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationName,
			&i.Dosage,
			&i.Frequency,
			&i.DurationDays,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
