// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedSession = `-- name: GetOwnedSession :one

SELECT s.id
FROM doctors_clinic_sessions s
JOIN doctors_profiles d ON d.id = s.doctor_profile_id
WHERE s.id = $1
  AND (
      d.user_id = $2
      OR EXISTS (
          SELECT 1 FROM identity_users u
          WHERE u.id = $2 AND u.role = 'Admin' AND u.deleted_at IS NULL
      )
  )
`

type GetOwnedSessionParams struct {
	ID     int64
	UserID int64
}

// Cross-module read: joins queue_entries with patients_profiles for display
// names, and doctors_clinic_sessions / doctors_profiles / identity_users
// for ownership. Permitted by R2.
func (q *Queries) GetOwnedSession(ctx context.Context, arg GetOwnedSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnedSession, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSessionQueue = `-- name: GetSessionQueue :many
SELECT
    qe.id, qe.queue_number, qe.status, qe.is_priority,
    qe.checked_in_at, qe.called_at, qe.started_at, qe.completed_at,
    p.full_name AS patient_full_name
FROM queue_entries qe
JOIN patients_profiles p ON p.id = qe.patient_profile_id
WHERE qe.clinic_session_id = $1
ORDER BY
    CASE WHEN qe.status IN ('Completed', 'NoShow', 'Cancelled') THEN 1 ELSE 0 END,
    qe.is_priority DESC,
    qe.queue_number ASC
`

type GetSessionQueueRow struct {
	ID              int64
	QueueNumber     int32
	Status          QueueStatus
	IsPriority      bool
	CheckedInAt     pgtype.Timestamptz
	CalledAt        pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	PatientFullName string
}

func (q *Queries) GetSessionQueue(ctx context.Context, clinicSessionID int64) ([]GetSessionQueueRow, error) {
	rows, err := q.db.Query(ctx, getSessionQueue, clinicSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionQueueRow
	for rows.Next() {
		var i GetSessionQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueNumber,
			&i.Status,
			&i.IsPriority,
			&i.CheckedInAt,
			&i.CalledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PatientFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWindowForSession = `-- name: GetWindowForSession :one
SELECT id, status, current_queue_entry_id, next_queue_number
FROM queue_windows
WHERE clinic_session_id = $1
`

type GetWindowForSessionRow struct {
	ID                  int64
	Status              QueueSessionStatus
	CurrentQueueEntryID *int64
	NextQueueNumber     int32
}

func (q *Queries) GetWindowForSession(ctx context.Context, clinicSessionID int64) (GetWindowForSessionRow, error) {
	row := q.db.QueryRow(ctx, getWindowForSession, clinicSessionID)
	var i GetWindowForSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentQueueEntryID,
		&i.NextQueueNumber,
	)
	return i, err
}
