// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE communication_notifications
SET is_read = true, read_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND is_read = false AND deleted_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
