// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDoctorProfileIDForUser = `-- name: GetDoctorProfileIDForUser :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorProfileIDForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileIDForUser, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFreeMessageForReply = `-- name: GetFreeMessageForReply :one
SELECT id, doctor_profile_id, sender_name, sender_email, content,
       is_replied_to, replied_at, reply_content,
       xmin::text AS xmin
FROM doctorposts_free_messages
WHERE id = $1
`

type GetFreeMessageForReplyRow struct {
	ID              int64
	DoctorProfileID int64
	SenderName      string
	SenderEmail     string
	Content         string
	IsRepliedTo     bool
	RepliedAt       pgtype.Timestamptz
	ReplyContent    *string
	Xmin            string
}

func (q *Queries) GetFreeMessageForReply(ctx context.Context, id int64) (GetFreeMessageForReplyRow, error) {
	row := q.db.QueryRow(ctx, getFreeMessageForReply, id)
	var i GetFreeMessageForReplyRow
	err := row.Scan(
		&i.ID,
		&i.DoctorProfileID,
		&i.SenderName,
		&i.SenderEmail,
		&i.Content,
		&i.IsRepliedTo,
		&i.RepliedAt,
		&i.ReplyContent,
		&i.Xmin,
	)
	return i, err
}

const updateReply = `-- name: UpdateReply :execrows
UPDATE doctorposts_free_messages
SET is_replied_to = true,
    replied_at = $2,
    reply_content = $3,
    updated_at = now()
WHERE id = $1 AND xmin::text = $4
`

type UpdateReplyParams struct {
	ID           int64
	RepliedAt    pgtype.Timestamptz
	ReplyContent *string
	Xmin         pgtype.Uint32
}

func (q *Queries) UpdateReply(ctx context.Context, arg UpdateReplyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReply,
		arg.ID,
		arg.RepliedAt,
		arg.ReplyContent,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
