// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blocksForDoctors = `-- name: BlocksForDoctors :many
SELECT doctor_profile_id, day_of_week, start_time, end_time,
       slot_duration_minutes, is_active
FROM doctors_weekly_schedules
WHERE doctor_profile_id = ANY($1::bigint[])
  AND is_active
`

type BlocksForDoctorsRow struct {
	DoctorProfileID     int64
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) BlocksForDoctors(ctx context.Context, doctorIds []int64) ([]BlocksForDoctorsRow, error) {
	rows, err := q.db.Query(ctx, blocksForDoctors, doctorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlocksForDoctorsRow
	for rows.Next() {
		var i BlocksForDoctorsRow
		if err := rows.Scan(
			&i.DoctorProfileID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDurationMinutes,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookedSlotsForDoctors = `-- name: BookedSlotsForDoctors :many
SELECT doctor_profile_id, scheduled_at
FROM consultations_consultations
WHERE doctor_profile_id = ANY($1::bigint[])
  AND scheduled_at >= $2
  AND scheduled_at < $3
  AND deleted_at IS NULL
  AND (
    status IN ('Confirmed', 'InProgress')
        OR (status = 'Pending' AND created_at > now() - INTERVAL '15 minutes')
    )
`

type BookedSlotsForDoctorsParams struct {
	DoctorIds []int64
	FromTs    pgtype.Timestamptz
	ToTs      pgtype.Timestamptz
}

type BookedSlotsForDoctorsRow struct {
	DoctorProfileID int64
	ScheduledAt     pgtype.Timestamptz
}

func (q *Queries) BookedSlotsForDoctors(ctx context.Context, arg BookedSlotsForDoctorsParams) ([]BookedSlotsForDoctorsRow, error) {
	rows, err := q.db.Query(ctx, bookedSlotsForDoctors, arg.DoctorIds, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookedSlotsForDoctorsRow
	for rows.Next() {
		var i BookedSlotsForDoctorsRow
		if err := rows.Scan(&i.DoctorProfileID, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exceptionsForDoctors = `-- name: ExceptionsForDoctors :many
SELECT doctor_profile_id, exception_date, from_time, to_time, type
FROM doctors_schedule_exceptions
WHERE doctor_profile_id = ANY($1::bigint[])
  AND exception_date BETWEEN $2 AND $3
  AND type = 'Closed'
`

type ExceptionsForDoctorsParams struct {
	DoctorIds []int64
	FromDate  pgtype.Date
	ToDate    pgtype.Date
}

type ExceptionsForDoctorsRow struct {
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
	FromTime        pgtype.Time
	ToTime          pgtype.Time
	Type            ScheduleExceptionType
}

func (q *Queries) ExceptionsForDoctors(ctx context.Context, arg ExceptionsForDoctorsParams) ([]ExceptionsForDoctorsRow, error) {
	rows, err := q.db.Query(ctx, exceptionsForDoctors, arg.DoctorIds, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExceptionsForDoctorsRow
	for rows.Next() {
		var i ExceptionsForDoctorsRow
		if err := rows.Scan(
			&i.DoctorProfileID,
			&i.ExceptionDate,
			&i.FromTime,
			&i.ToTime,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDoctorsByCreatedAt = `-- name: SearchDoctorsByCreatedAt :many
SELECT
    d.id, d.full_name, d.bio, d.clinic_name,
    d.consultation_fee::text AS consultation_fee,
    d.currency,
    d.average_rating::text   AS average_rating,
    d.rating_count,
    u.profile_image_file_id, -- ✅ ADDED
    u.profile_image_url,
    d.created_at
FROM doctors_profiles d
         JOIN identity_users u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND d.verification_status = 'Verified'
  AND ($1::text IS NULL
       OR d.full_name   ILIKE '%' || $1 || '%'
       OR d.clinic_name ILIKE '%' || $1 || '%'
       OR d.bio         ILIKE '%' || $1 || '%')
  AND ($2::bigint[] IS NULL
       OR EXISTS (
           SELECT 1 FROM doctors_profile_specialties dps
           WHERE dps.doctor_profile_id = d.id
             AND dps.specialty_id = ANY($2::bigint[])
       ))
  AND ($3::numeric IS NULL OR d.consultation_fee >= $3)
  AND ($4::numeric IS NULL OR d.consultation_fee <= $4)
  AND ($5::numeric IS NULL OR d.average_rating >= $5)
  AND ($6::timestamptz IS NULL
       OR (d.created_at, d.id) < ($6::timestamptz, $7::bigint))
ORDER BY d.created_at DESC, d.id DESC
    LIMIT $8
`

type SearchDoctorsByCreatedAtParams struct {
	Q               pgtype.Text
	SpecialtyIds    []int64
	MinFee          pgtype.Numeric
	MaxFee          pgtype.Numeric
	MinRating       pgtype.Numeric
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.Int8
	LimitCount      int32
}

type SearchDoctorsByCreatedAtRow struct {
	ID                 int64
	FullName           string
	Bio                string
	ClinicName         string
	ConsultationFee    string
	Currency           string
	AverageRating      string
	RatingCount        int32
	ProfileImageFileID pgtype.Int8
	ProfileImageUrl    pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) SearchDoctorsByCreatedAt(ctx context.Context, arg SearchDoctorsByCreatedAtParams) ([]SearchDoctorsByCreatedAtRow, error) {
	rows, err := q.db.Query(ctx, searchDoctorsByCreatedAt,
		arg.Q,
		arg.SpecialtyIds,
		arg.MinFee,
		arg.MaxFee,
		arg.MinRating,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDoctorsByCreatedAtRow
	for rows.Next() {
		var i SearchDoctorsByCreatedAtRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Bio,
			&i.ClinicName,
			&i.ConsultationFee,
			&i.Currency,
			&i.AverageRating,
			&i.RatingCount,
			&i.ProfileImageFileID,
			&i.ProfileImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDoctorsByFeeAsc = `-- name: SearchDoctorsByFeeAsc :many
SELECT
    d.id, d.full_name, d.bio, d.clinic_name,
    d.consultation_fee::text AS consultation_fee,
    d.currency,
    d.average_rating::text   AS average_rating,
    d.rating_count,
    u.profile_image_file_id, -- ✅ ADDED
    u.profile_image_url,
    d.created_at
FROM doctors_profiles d
         JOIN identity_users u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND d.verification_status = 'Verified'
  AND ($1::text IS NULL
       OR d.full_name   ILIKE '%' || $1 || '%'
       OR d.clinic_name ILIKE '%' || $1 || '%'
       OR d.bio         ILIKE '%' || $1 || '%')
  AND ($2::bigint[] IS NULL
       OR EXISTS (
           SELECT 1 FROM doctors_profile_specialties dps
           WHERE dps.doctor_profile_id = d.id
             AND dps.specialty_id = ANY($2::bigint[])
       ))
  AND ($3::numeric IS NULL OR d.consultation_fee >= $3)
  AND ($4::numeric IS NULL OR d.consultation_fee <= $4)
  AND ($5::numeric IS NULL OR d.average_rating >= $5)
  AND ($6::numeric IS NULL
       OR d.consultation_fee > $6
       OR (d.consultation_fee = $6 AND d.id < $7))
ORDER BY d.consultation_fee ASC, d.id DESC
    LIMIT $8
`

type SearchDoctorsByFeeAscParams struct {
	Q            pgtype.Text
	SpecialtyIds []int64
	MinFee       pgtype.Numeric
	MaxFee       pgtype.Numeric
	MinRating    pgtype.Numeric
	CursorFee    pgtype.Numeric
	CursorID     pgtype.Int8
	LimitCount   int32
}

type SearchDoctorsByFeeAscRow struct {
	ID                 int64
	FullName           string
	Bio                string
	ClinicName         string
	ConsultationFee    string
	Currency           string
	AverageRating      string
	RatingCount        int32
	ProfileImageFileID pgtype.Int8
	ProfileImageUrl    pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) SearchDoctorsByFeeAsc(ctx context.Context, arg SearchDoctorsByFeeAscParams) ([]SearchDoctorsByFeeAscRow, error) {
	rows, err := q.db.Query(ctx, searchDoctorsByFeeAsc,
		arg.Q,
		arg.SpecialtyIds,
		arg.MinFee,
		arg.MaxFee,
		arg.MinRating,
		arg.CursorFee,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDoctorsByFeeAscRow
	for rows.Next() {
		var i SearchDoctorsByFeeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Bio,
			&i.ClinicName,
			&i.ConsultationFee,
			&i.Currency,
			&i.AverageRating,
			&i.RatingCount,
			&i.ProfileImageFileID,
			&i.ProfileImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDoctorsByFeeDesc = `-- name: SearchDoctorsByFeeDesc :many
SELECT
    d.id, d.full_name, d.bio, d.clinic_name,
    d.consultation_fee::text AS consultation_fee,
    d.currency,
    d.average_rating::text   AS average_rating,
    d.rating_count,
    u.profile_image_file_id, -- ✅ ADDED
    u.profile_image_url,
    d.created_at
FROM doctors_profiles d
         JOIN identity_users u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND d.verification_status = 'Verified'
  AND ($1::text IS NULL
       OR d.full_name   ILIKE '%' || $1 || '%'
       OR d.clinic_name ILIKE '%' || $1 || '%'
       OR d.bio         ILIKE '%' || $1 || '%')
  AND ($2::bigint[] IS NULL
       OR EXISTS (
           SELECT 1 FROM doctors_profile_specialties dps
           WHERE dps.doctor_profile_id = d.id
             AND dps.specialty_id = ANY($2::bigint[])
       ))
  AND ($3::numeric IS NULL OR d.consultation_fee >= $3)
  AND ($4::numeric IS NULL OR d.consultation_fee <= $4)
  AND ($5::numeric IS NULL OR d.average_rating >= $5)
  AND ($6::numeric IS NULL
       OR (d.consultation_fee, d.id) < ($6::numeric, $7::bigint))
ORDER BY d.consultation_fee DESC, d.id DESC
    LIMIT $8
`

type SearchDoctorsByFeeDescParams struct {
	Q            pgtype.Text
	SpecialtyIds []int64
	MinFee       pgtype.Numeric
	MaxFee       pgtype.Numeric
	MinRating    pgtype.Numeric
	CursorFee    pgtype.Numeric
	CursorID     pgtype.Int8
	LimitCount   int32
}

type SearchDoctorsByFeeDescRow struct {
	ID                 int64
	FullName           string
	Bio                string
	ClinicName         string
	ConsultationFee    string
	Currency           string
	AverageRating      string
	RatingCount        int32
	ProfileImageFileID pgtype.Int8
	ProfileImageUrl    pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) SearchDoctorsByFeeDesc(ctx context.Context, arg SearchDoctorsByFeeDescParams) ([]SearchDoctorsByFeeDescRow, error) {
	rows, err := q.db.Query(ctx, searchDoctorsByFeeDesc,
		arg.Q,
		arg.SpecialtyIds,
		arg.MinFee,
		arg.MaxFee,
		arg.MinRating,
		arg.CursorFee,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDoctorsByFeeDescRow
	for rows.Next() {
		var i SearchDoctorsByFeeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Bio,
			&i.ClinicName,
			&i.ConsultationFee,
			&i.Currency,
			&i.AverageRating,
			&i.RatingCount,
			&i.ProfileImageFileID,
			&i.ProfileImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDoctorsByRating = `-- name: SearchDoctorsByRating :many

SELECT
    d.id, d.full_name, d.bio, d.clinic_name,
    d.consultation_fee::text AS consultation_fee,
    d.currency,
    d.average_rating::text   AS average_rating,
    d.rating_count,
    u.profile_image_file_id, -- ✅ FIXED: Removed duplicate profile_image_url
    u.profile_image_url,
    d.created_at
FROM doctors_profiles d
         JOIN identity_users u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE d.deleted_at IS NULL
  AND d.verification_status = 'Verified'
  AND ($1::text IS NULL
       OR d.full_name   ILIKE '%' || $1 || '%'
       OR d.clinic_name ILIKE '%' || $1 || '%'
       OR d.bio         ILIKE '%' || $1 || '%')
  AND ($2::bigint[] IS NULL
       OR EXISTS (
           SELECT 1 FROM doctors_profile_specialties dps
           WHERE dps.doctor_profile_id = d.id
             AND dps.specialty_id = ANY($2::bigint[])
       ))
  AND ($3::numeric IS NULL OR d.consultation_fee >= $3)
  AND ($4::numeric IS NULL OR d.consultation_fee <= $4)
  AND ($5::numeric IS NULL OR d.average_rating >= $5)
  AND ($6::numeric IS NULL
       OR (d.average_rating, d.id) < ($6::numeric, $7::bigint))
ORDER BY d.average_rating DESC, d.id DESC
    LIMIT $8
`

type SearchDoctorsByRatingParams struct {
	Q            pgtype.Text
	SpecialtyIds []int64
	MinFee       pgtype.Numeric
	MaxFee       pgtype.Numeric
	MinRating    pgtype.Numeric
	CursorRating pgtype.Numeric
	CursorID     pgtype.Int8
	LimitCount   int32
}

type SearchDoctorsByRatingRow struct {
	ID                 int64
	FullName           string
	Bio                string
	ClinicName         string
	ConsultationFee    string
	Currency           string
	AverageRating      string
	RatingCount        int32
	ProfileImageFileID pgtype.Int8
	ProfileImageUrl    pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

// Cross-module read: joins identity_users (Identity) with
// doctors_profiles and friends (Doctors). Permitted by R2
// (docs/phase-1/00-decisions.md). Writes never cross modules.
func (q *Queries) SearchDoctorsByRating(ctx context.Context, arg SearchDoctorsByRatingParams) ([]SearchDoctorsByRatingRow, error) {
	rows, err := q.db.Query(ctx, searchDoctorsByRating,
		arg.Q,
		arg.SpecialtyIds,
		arg.MinFee,
		arg.MaxFee,
		arg.MinRating,
		arg.CursorRating,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDoctorsByRatingRow
	for rows.Next() {
		var i SearchDoctorsByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Bio,
			&i.ClinicName,
			&i.ConsultationFee,
			&i.Currency,
			&i.AverageRating,
			&i.RatingCount,
			&i.ProfileImageFileID,
			&i.ProfileImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specialtiesForDoctors = `-- name: SpecialtiesForDoctors :many
SELECT dps.doctor_profile_id, s.id AS specialty_id, s.name
FROM doctors_profile_specialties dps
         JOIN doctors_specialties s ON s.id = dps.specialty_id
WHERE dps.doctor_profile_id = ANY($1::bigint[])
ORDER BY s.name
`

type SpecialtiesForDoctorsRow struct {
	DoctorProfileID int64
	SpecialtyID     int64
	Name            string
}

func (q *Queries) SpecialtiesForDoctors(ctx context.Context, doctorIds []int64) ([]SpecialtiesForDoctorsRow, error) {
	rows, err := q.db.Query(ctx, specialtiesForDoctors, doctorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecialtiesForDoctorsRow
	for rows.Next() {
		var i SpecialtiesForDoctorsRow
		if err := rows.Scan(&i.DoctorProfileID, &i.SpecialtyID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
