// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const closeWindow = `-- name: CloseWindow :execrows
UPDATE queue_windows
SET status = 'Closed', updated_at = now()
WHERE id = $1 AND xmin::text = $2::text
`

type CloseWindowParams struct {
	ID   int64
	Xmin string
}

func (q *Queries) CloseWindow(ctx context.Context, arg CloseWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeWindow, arg.ID, arg.Xmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failRemainingEntries = `-- name: FailRemainingEntries :execrows
UPDATE queue_entries
SET status = 'NoShow',
    skip_reason = 'session closed',
    updated_at = now()
WHERE queue_window_id = $1
  AND status IN ('Waiting', 'Called', 'Skipped')
`

func (q *Queries) FailRemainingEntries(ctx context.Context, queueWindowID int64) (int64, error) {
	result, err := q.db.Exec(ctx, failRemainingEntries, queueWindowID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWindowBySessionForUpdate = `-- name: GetWindowBySessionForUpdate :one
SELECT qw.id, qw.status, qw.xmin::text AS xmin
FROM queue_windows qw
JOIN doctors_clinic_sessions s ON s.id = qw.clinic_session_id
JOIN doctors_profiles d ON d.id = s.doctor_profile_id
WHERE qw.clinic_session_id = $1
  AND (
      d.user_id = $2
      OR EXISTS (
          SELECT 1 FROM identity_users u
          WHERE u.id = $2 AND u.role = 'Admin' AND u.deleted_at IS NULL
      )
  )
FOR UPDATE
`

type GetWindowBySessionForUpdateParams struct {
	ClinicSessionID int64
	UserID          int64
}

type GetWindowBySessionForUpdateRow struct {
	ID     int64
	Status QueueSessionStatus
	Xmin   string
}

// Doctor of the session or admin. Ownership in SQL (anti-enumeration).
func (q *Queries) GetWindowBySessionForUpdate(ctx context.Context, arg GetWindowBySessionForUpdateParams) (GetWindowBySessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWindowBySessionForUpdate, arg.ClinicSessionID, arg.UserID)
	var i GetWindowBySessionForUpdateRow
	err := row.Scan(&i.ID, &i.Status, &i.Xmin)
	return i, err
}
