// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAhead = `-- name: CountAhead :one
SELECT COUNT(*)::int AS n
FROM queue_entries
WHERE queue_window_id = $1
  AND id != $2
  AND status IN ('Waiting', 'Called', 'Skipped')
  AND (
      (is_priority = true AND $3::boolean = false)
      OR (is_priority = $3::boolean AND queue_number < $4)
  )
`

type CountAheadParams struct {
	QueueWindowID int64
	ID            int64
	IsPriority    bool
	QueueNumber   int32
}

func (q *Queries) CountAhead(ctx context.Context, arg CountAheadParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAhead,
		arg.QueueWindowID,
		arg.ID,
		arg.IsPriority,
		arg.QueueNumber,
	)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const ensureWindow = `-- name: EnsureWindow :one
INSERT INTO queue_windows (clinic_session_id, status)
VALUES ($1, 'Open')
ON CONFLICT (clinic_session_id) DO UPDATE
    SET updated_at = queue_windows.updated_at  -- no-op to fire RETURNING
RETURNING id
`

func (q *Queries) EnsureWindow(ctx context.Context, clinicSessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, ensureWindow, clinicSessionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getExistingEntryForConsultation = `-- name: GetExistingEntryForConsultation :one
SELECT id, queue_number, is_priority, status, checked_in_at, queue_window_id
FROM queue_entries
WHERE consultation_id = $1
`

type GetExistingEntryForConsultationRow struct {
	ID            int64
	QueueNumber   int32
	IsPriority    bool
	Status        QueueStatus
	CheckedInAt   pgtype.Timestamptz
	QueueWindowID int64
}

func (q *Queries) GetExistingEntryForConsultation(ctx context.Context, consultationID int64) (GetExistingEntryForConsultationRow, error) {
	row := q.db.QueryRow(ctx, getExistingEntryForConsultation, consultationID)
	var i GetExistingEntryForConsultationRow
	err := row.Scan(
		&i.ID,
		&i.QueueNumber,
		&i.IsPriority,
		&i.Status,
		&i.CheckedInAt,
		&i.QueueWindowID,
	)
	return i, err
}

const getWindowForUpdate = `-- name: GetWindowForUpdate :one
SELECT id, clinic_session_id, status, next_queue_number,
       current_queue_entry_id, xmin::text AS xmin
FROM queue_windows
WHERE clinic_session_id = $1
FOR UPDATE
`

type GetWindowForUpdateRow struct {
	ID                  int64
	ClinicSessionID     int64
	Status              QueueSessionStatus
	NextQueueNumber     int32
	CurrentQueueEntryID *int64
	Xmin                string
}

// Ensures the window exists then locks it. Called AFTER EnsureWindow.
func (q *Queries) GetWindowForUpdate(ctx context.Context, clinicSessionID int64) (GetWindowForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWindowForUpdate, clinicSessionID)
	var i GetWindowForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ClinicSessionID,
		&i.Status,
		&i.NextQueueNumber,
		&i.CurrentQueueEntryID,
		&i.Xmin,
	)
	return i, err
}

const incrementQueueNumber = `-- name: IncrementQueueNumber :one
UPDATE queue_windows
SET next_queue_number = next_queue_number + 1,
    updated_at = now()
WHERE id = $1
RETURNING next_queue_number - 1 AS assigned_number
`

func (q *Queries) IncrementQueueNumber(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementQueueNumber, id)
	var assigned_number int32
	err := row.Scan(&assigned_number)
	return assigned_number, err
}

const insertQueueEntry = `-- name: InsertQueueEntry :one
INSERT INTO queue_entries (
    consultation_id, queue_window_id, clinic_session_id, patient_profile_id,
    queue_number, is_priority, status, checked_in_at
) VALUES ($1, $2, $3, $4, $5, $6, 'Waiting', now())
RETURNING id, created_at
`

type InsertQueueEntryParams struct {
	ConsultationID   int64
	QueueWindowID    int64
	ClinicSessionID  int64
	PatientProfileID int64
	QueueNumber      int32
	IsPriority       bool
}

type InsertQueueEntryRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertQueueEntry(ctx context.Context, arg InsertQueueEntryParams) (InsertQueueEntryRow, error) {
	row := q.db.QueryRow(ctx, insertQueueEntry,
		arg.ConsultationID,
		arg.QueueWindowID,
		arg.ClinicSessionID,
		arg.PatientProfileID,
		arg.QueueNumber,
		arg.IsPriority,
	)
	var i InsertQueueEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
