// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getClinicalContext = `-- name: GetClinicalContext :one

SELECT
    c.id, c.patient_profile_id, c.doctor_profile_id, c.status
FROM consultations_consultations c
         JOIN doctors_profiles d ON d.id = c.doctor_profile_id
WHERE c.id = $1
  AND d.user_id = $2
  AND c.deleted_at IS NULL
`

type GetClinicalContextParams struct {
	ID     int64
	UserID int64
}

type GetClinicalContextRow struct {
	ID               int64
	PatientProfileID int64
	DoctorProfileID  int64
	Status           ConsultationStatus
}

// Cross-module read: joins consultations_consultations (Consultations)
// with doctors_profiles (Doctors) to verify the caller is the treating
// doctor. Permitted by R2.
func (q *Queries) GetClinicalContext(ctx context.Context, arg GetClinicalContextParams) (GetClinicalContextRow, error) {
	row := q.db.QueryRow(ctx, getClinicalContext, arg.ID, arg.UserID)
	var i GetClinicalContextRow
	err := row.Scan(
		&i.ID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.Status,
	)
	return i, err
}
