// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFeed = `-- name: ListFeed :many

SELECT
    p.id, p.title, COALESCE(p.excerpt, '') AS excerpt, p.type, p.cover_image_url,
    p.view_count, p.like_count, COALESCE(p.published_at, p.created_at) AS published_at,
    d.id AS doctor_id, d.full_name AS doctor_full_name,
    u.profile_image_url AS doctor_profile_image_url
FROM content_posts p
JOIN doctors_profiles d ON d.id = p.doctor_profile_id AND d.deleted_at IS NULL
JOIN identity_users  u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE p.is_published = true AND p.deleted_at IS NULL
  AND ($1::post_type IS NULL OR p.type = $1)
  AND ($2::text IS NULL
       OR p.title ILIKE '%' || $2 || '%'
       OR COALESCE(p.excerpt, '') ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL
       OR $3::boolean = false
       OR p.is_featured = true)
  AND ($4::timestamptz IS NULL
       OR (COALESCE(p.published_at, p.created_at), p.id) < ($4::timestamptz, $5::bigint))
ORDER BY COALESCE(p.published_at, p.created_at) DESC, p.id DESC
LIMIT $6
`

type ListFeedParams struct {
	Type              NullPostType
	Q                 pgtype.Text
	FeaturedOnly      pgtype.Bool
	CursorPublishedAt pgtype.Timestamptz
	CursorID          pgtype.Int8
	LimitCount        int32
}

type ListFeedRow struct {
	ID                    int64
	Title                 string
	Excerpt               string
	Type                  PostType
	CoverImageUrl         pgtype.Text
	ViewCount             int32
	LikeCount             int32
	PublishedAt           pgtype.Timestamptz
	DoctorID              int64
	DoctorFullName        string
	DoctorProfileImageUrl pgtype.Text
}

// Cross-module read: joins doctors_profiles and identity_users.
func (q *Queries) ListFeed(ctx context.Context, arg ListFeedParams) ([]ListFeedRow, error) {
	rows, err := q.db.Query(ctx, listFeed,
		arg.Type,
		arg.Q,
		arg.FeaturedOnly,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedRow
	for rows.Next() {
		var i ListFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Type,
			&i.CoverImageUrl,
			&i.ViewCount,
			&i.LikeCount,
			&i.PublishedAt,
			&i.DoctorID,
			&i.DoctorFullName,
			&i.DoctorProfileImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specialties = `-- name: Specialties :many
SELECT dps.doctor_profile_id, s.name
FROM doctors_profile_specialties dps
JOIN doctors_specialties s ON s.id = dps.specialty_id
WHERE dps.doctor_profile_id = ANY($1::bigint[])
ORDER BY s.name
`

type SpecialtiesRow struct {
	DoctorProfileID int64
	Name            string
}

func (q *Queries) Specialties(ctx context.Context, doctorIds []int64) ([]SpecialtiesRow, error) {
	rows, err := q.db.Query(ctx, specialties, doctorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecialtiesRow
	for rows.Next() {
		var i SpecialtiesRow
		if err := rows.Scan(&i.DoctorProfileID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
