// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAhead = `-- name: CountAhead :one
SELECT COUNT(*)::int AS n
FROM queue_entries
WHERE queue_window_id = $1
  AND id != $2
  AND status IN ('Waiting', 'Called', 'Skipped')
  AND (
      (is_priority = true AND $3::boolean = false)
      OR (is_priority = $3::boolean AND queue_number < $4)
  )
`

type CountAheadParams struct {
	QueueWindowID int64
	ID            int64
	IsPriority    bool
	QueueNumber   int32
}

func (q *Queries) CountAhead(ctx context.Context, arg CountAheadParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAhead,
		arg.QueueWindowID,
		arg.ID,
		arg.IsPriority,
		arg.QueueNumber,
	)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const getPatientQueueView = `-- name: GetPatientQueueView :one

SELECT
    qe.id, qe.queue_number, qe.status, qe.is_priority, qe.checked_in_at,
    qe.queue_window_id,
    qw.current_queue_entry_id,
    c_qe.queue_number AS current_queue_number,
    c_qe.status       AS current_queue_status,
    c_qe.started_at   AS current_started_at
FROM queue_entries qe
JOIN queue_windows qw ON qw.id = qe.queue_window_id
LEFT JOIN queue_entries c_qe ON c_qe.id = qw.current_queue_entry_id
JOIN consultations_consultations c ON c.id = qe.consultation_id
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles d ON d.id = c.doctor_profile_id
WHERE qe.consultation_id = $1
  AND qe.status NOT IN ('NoShow', 'Cancelled')
  AND (p.user_id = $2 OR d.user_id = $2)
`

type GetPatientQueueViewParams struct {
	ConsultationID int64
	UserID         int64
}

type GetPatientQueueViewRow struct {
	ID                  int64
	QueueNumber         int32
	Status              QueueStatus
	IsPriority          bool
	CheckedInAt         pgtype.Timestamptz
	QueueWindowID       int64
	CurrentQueueEntryID *int64
	CurrentQueueNumber  *int32
	CurrentQueueStatus  NullQueueStatus
	CurrentStartedAt    pgtype.Timestamptz
}

// Cross-module read: joins queue_entries with consultations_consultations,
// patients_profiles and doctors_profiles for participant ownership (R2).
func (q *Queries) GetPatientQueueView(ctx context.Context, arg GetPatientQueueViewParams) (GetPatientQueueViewRow, error) {
	row := q.db.QueryRow(ctx, getPatientQueueView, arg.ConsultationID, arg.UserID)
	var i GetPatientQueueViewRow
	err := row.Scan(
		&i.ID,
		&i.QueueNumber,
		&i.Status,
		&i.IsPriority,
		&i.CheckedInAt,
		&i.QueueWindowID,
		&i.CurrentQueueEntryID,
		&i.CurrentQueueNumber,
		&i.CurrentQueueStatus,
		&i.CurrentStartedAt,
	)
	return i, err
}
