// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelStalePending = `-- name: CancelStalePending :exec
UPDATE consultations_consultations
SET status = 'Cancelled', updated_at = now()
WHERE doctor_profile_id = $1
  AND scheduled_at = $2
  AND status = 'Pending'
  AND created_at <= now() - INTERVAL '15 minutes'
  AND deleted_at IS NULL
`

type CancelStalePendingParams struct {
	DoctorProfileID int64
	ScheduledAt     pgtype.Timestamptz
}

func (q *Queries) CancelStalePending(ctx context.Context, arg CancelStalePendingParams) error {
	_, err := q.db.Exec(ctx, cancelStalePending, arg.DoctorProfileID, arg.ScheduledAt)
	return err
}

const countActiveSlot = `-- name: CountActiveSlot :one
SELECT COUNT(*)::bigint AS n
FROM consultations_consultations
WHERE doctor_profile_id = $1
  AND scheduled_at = $2
  AND deleted_at IS NULL
  AND (
    status IN ('Confirmed', 'InProgress')
        OR (status = 'Pending' AND created_at > now() - INTERVAL '15 minutes')
    )
`

type CountActiveSlotParams struct {
	DoctorProfileID int64
	ScheduledAt     pgtype.Timestamptz
}

func (q *Queries) CountActiveSlot(ctx context.Context, arg CountActiveSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSlot, arg.DoctorProfileID, arg.ScheduledAt)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const getDoctorUserID = `-- name: GetDoctorUserID :one
SELECT user_id FROM doctors_profiles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorUserID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorUserID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getPatientProfileForUser = `-- name: GetPatientProfileForUser :one
SELECT id FROM patients_profiles WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPatientProfileForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPatientProfileForUser, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertConsultation = `-- name: InsertConsultation :one
INSERT INTO consultations_consultations (
    patient_profile_id, doctor_profile_id, clinic_session_id,
    scheduled_at, duration_minutes, is_urgent, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertConsultationParams struct {
	PatientProfileID int64
	DoctorProfileID  int64
	ClinicSessionID  pgtype.Int8
	ScheduledAt      pgtype.Timestamptz
	DurationMinutes  int32
	IsUrgent         bool
	Notes            pgtype.Text
}

type InsertConsultationRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertConsultation(ctx context.Context, arg InsertConsultationParams) (InsertConsultationRow, error) {
	row := q.db.QueryRow(ctx, insertConsultation,
		arg.PatientProfileID,
		arg.DoctorProfileID,
		arg.ClinicSessionID,
		arg.ScheduledAt,
		arg.DurationMinutes,
		arg.IsUrgent,
		arg.Notes,
	)
	var i InsertConsultationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const lockSession = `-- name: LockSession :one
SELECT id FROM doctors_clinic_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	err := row.Scan(&id)
	return id, err
}
