// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileForSubmission = `-- name: GetProfileForSubmission :one
SELECT id, user_id, full_name, bio,
       consultation_fee::text AS consultation_fee,
    currency, clinic_name, clinic_address, medical_license_number,
       verification_status, submitted_at,
       xmin::text AS xmin
FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetProfileForSubmissionRow struct {
	ID                   int64
	UserID               int64
	FullName             string
	Bio                  string
	ConsultationFee      string
	Currency             string
	ClinicName           string
	ClinicAddress        string
	MedicalLicenseNumber pgtype.Text
	VerificationStatus   VerificationStatus
	SubmittedAt          pgtype.Timestamptz
	Xmin                 string
}

func (q *Queries) GetProfileForSubmission(ctx context.Context, userID int64) (GetProfileForSubmissionRow, error) {
	row := q.db.QueryRow(ctx, getProfileForSubmission, userID)
	var i GetProfileForSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Bio,
		&i.ConsultationFee,
		&i.Currency,
		&i.ClinicName,
		&i.ClinicAddress,
		&i.MedicalLicenseNumber,
		&i.VerificationStatus,
		&i.SubmittedAt,
		&i.Xmin,
	)
	return i, err
}

const listSpecialtyIDs = `-- name: ListSpecialtyIDs :many
SELECT specialty_id
FROM doctors_profile_specialties
WHERE doctor_profile_id = $1
`

func (q *Queries) ListSpecialtyIDs(ctx context.Context, doctorProfileID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listSpecialtyIDs, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var specialty_id int64
		if err := rows.Scan(&specialty_id); err != nil {
			return nil, err
		}
		items = append(items, specialty_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVerificationStatus = `-- name: UpdateVerificationStatus :execrows
UPDATE doctors_profiles
SET verification_status = $1,
    submitted_at        = $2,
    updated_at          = now()
WHERE id = $3 AND xmin::text = $4
`

type UpdateVerificationStatusParams struct {
	VerificationStatus VerificationStatus
	SubmittedAt        pgtype.Timestamptz
	ID                 int64
	Xmin               pgtype.Uint32
}

func (q *Queries) UpdateVerificationStatus(ctx context.Context, arg UpdateVerificationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVerificationStatus,
		arg.VerificationStatus,
		arg.SubmittedAt,
		arg.ID,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
