// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllBlocks = `-- name: DeleteAllBlocks :exec
DELETE FROM doctors_weekly_schedules WHERE doctor_profile_id = $1
`

func (q *Queries) DeleteAllBlocks(ctx context.Context, doctorProfileID int64) error {
	_, err := q.db.Exec(ctx, deleteAllBlocks, doctorProfileID)
	return err
}

const getDoctorProfileIDForSchedule = `-- name: GetDoctorProfileIDForSchedule :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorProfileIDForSchedule(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileIDForSchedule, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO doctors_weekly_schedules (
    doctor_profile_id, day_of_week, start_time, end_time,
    slot_duration_minutes, is_active
) VALUES ($1, $2, $3::time, $4::time, $5, $6)
`

type InsertBlockParams struct {
	DoctorProfileID     int64
	DayOfWeek           int16
	Column3             pgtype.Time
	Column4             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.DoctorProfileID,
		arg.DayOfWeek,
		arg.Column3,
		arg.Column4,
		arg.SlotDurationMinutes,
		arg.IsActive,
	)
	return err
}
