// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const softDeleteFile = `-- name: SoftDeleteFile :one
UPDATE platform_files
SET deleted_at = now()
WHERE id = $1 AND uploader_id = $2 AND deleted_at IS NULL
    RETURNING object_key
`

type SoftDeleteFileParams struct {
	ID         int64
	UploaderID int64
}

func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteFile, arg.ID, arg.UploaderID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}
