// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)::bigint
FROM communication_notifications
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, payload, is_read, read_at, created_at
FROM communication_notifications
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListNotificationsRow struct {
	ID        int64
	UserID    int64
	Type      string
	Title     string
	Body      string
	Payload   []byte
	IsRead    bool
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
