// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const markAllRead = `-- name: MarkAllRead :execrows
UPDATE communication_notifications
SET is_read = true, read_at = now(), updated_at = now()
WHERE user_id = $1 AND is_read = false AND deleted_at IS NULL
`

func (q *Queries) MarkAllRead(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
