// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSpecialties = `-- name: ListSpecialties :many
SELECT id, name, parent_specialty_id
FROM doctors_specialties
ORDER BY id
`

type ListSpecialtiesRow struct {
	ID                int64
	Name              string
	ParentSpecialtyID pgtype.Int8
}

func (q *Queries) ListSpecialties(ctx context.Context) ([]ListSpecialtiesRow, error) {
	rows, err := q.db.Query(ctx, listSpecialties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecialtiesRow
	for rows.Next() {
		var i ListSpecialtiesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentSpecialtyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
