// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSuspension = `-- name: GetActiveSuspension :one
SELECT reason, from_ts, to_ts
FROM admin_user_suspensions
WHERE user_id = $1
  AND lifted_at IS NULL
  AND (to_ts IS NULL OR to_ts > now())
ORDER BY from_ts DESC
LIMIT 1
`

type GetActiveSuspensionRow struct {
	Reason string
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
}

func (q *Queries) GetActiveSuspension(ctx context.Context, userID int64) (GetActiveSuspensionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSuspension, userID)
	var i GetActiveSuspensionRow
	err := row.Scan(&i.Reason, &i.FromTs, &i.ToTs)
	return i, err
}
