// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const doctorExists = `-- name: DoctorExists :one
SELECT id FROM doctors_profiles
WHERE id = $1 AND deleted_at IS NULL AND verification_status = 'Verified'
`

func (q *Queries) DoctorExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, doctorExists, id)
	err := row.Scan(&id)
	return id, err
}

const listByDoctor = `-- name: ListByDoctor :many
SELECT
    p.id, p.title, COALESCE(p.excerpt, '') AS excerpt, p.type, p.cover_image_url,
    p.view_count, p.like_count, COALESCE(p.published_at, p.created_at) AS published_at,
    d.id AS doctor_id, d.full_name AS doctor_full_name,
    u.profile_image_url AS doctor_profile_image_url
FROM content_posts p
JOIN doctors_profiles d ON d.id = p.doctor_profile_id AND d.deleted_at IS NULL
JOIN identity_users  u ON u.id = d.user_id AND u.deleted_at IS NULL
WHERE p.is_published = true
  AND p.deleted_at IS NULL
  AND p.doctor_profile_id = $1::bigint
  AND ($2::timestamptz IS NULL
       OR (COALESCE(p.published_at, p.created_at), p.id) < ($2::timestamptz, $3::bigint))
ORDER BY COALESCE(p.published_at, p.created_at) DESC, p.id DESC
LIMIT $4
`

type ListByDoctorParams struct {
	DoctorProfileID   int64
	CursorPublishedAt pgtype.Timestamptz
	CursorID          pgtype.Int8
	LimitCount        int32
}

type ListByDoctorRow struct {
	ID                    int64
	Title                 string
	Excerpt               string
	Type                  PostType
	CoverImageUrl         pgtype.Text
	ViewCount             int32
	LikeCount             int32
	PublishedAt           pgtype.Timestamptz
	DoctorID              int64
	DoctorFullName        string
	DoctorProfileImageUrl pgtype.Text
}

func (q *Queries) ListByDoctor(ctx context.Context, arg ListByDoctorParams) ([]ListByDoctorRow, error) {
	rows, err := q.db.Query(ctx, listByDoctor,
		arg.DoctorProfileID,
		arg.CursorPublishedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByDoctorRow
	for rows.Next() {
		var i ListByDoctorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Type,
			&i.CoverImageUrl,
			&i.ViewCount,
			&i.LikeCount,
			&i.PublishedAt,
			&i.DoctorID,
			&i.DoctorFullName,
			&i.DoctorProfileImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specialties = `-- name: Specialties :many
SELECT s.name
FROM doctors_profile_specialties dps
JOIN doctors_specialties s ON s.id = dps.specialty_id
WHERE dps.doctor_profile_id = $1
ORDER BY s.name
`

func (q *Queries) Specialties(ctx context.Context, doctorProfileID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, specialties, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
