// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDoctorForFreeMessage = `-- name: GetDoctorForFreeMessage :one
SELECT id FROM doctors_profiles
WHERE id = $1 AND verification_status = 'Verified' AND deleted_at IS NULL
`

func (q *Queries) GetDoctorForFreeMessage(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorForFreeMessage, id)
	err := row.Scan(&id)
	return id, err
}

const insertFreeMessage = `-- name: InsertFreeMessage :one
INSERT INTO doctorposts_free_messages (
    doctor_profile_id, sender_name, sender_email, sender_phone,
    content, sender_ip
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertFreeMessageParams struct {
	DoctorProfileID int64
	SenderName      string
	SenderEmail     string
	SenderPhone     *string
	Content         string
	SenderIp        *netip.Addr
}

type InsertFreeMessageRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertFreeMessage(ctx context.Context, arg InsertFreeMessageParams) (InsertFreeMessageRow, error) {
	row := q.db.QueryRow(ctx, insertFreeMessage,
		arg.DoctorProfileID,
		arg.SenderName,
		arg.SenderEmail,
		arg.SenderPhone,
		arg.Content,
		arg.SenderIp,
	)
	var i InsertFreeMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
