// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMedicationsForPrescription = `-- name: DeleteMedicationsForPrescription :exec
UPDATE clinical_prescribed_medications
SET deleted_at = now(), updated_at = now()
WHERE prescription_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteMedicationsForPrescription(ctx context.Context, prescriptionID int64) error {
	_, err := q.db.Exec(ctx, deleteMedicationsForPrescription, prescriptionID)
	return err
}

const getPrescriptionByConsultation = `-- name: GetPrescriptionByConsultation :one
SELECT id, consultation_id, patient_profile_id, doctor_profile_id,
       issued_at, created_at, updated_at,
       xmin::text AS xmin
FROM clinical_prescriptions
WHERE consultation_id = $1 AND deleted_at IS NULL
`

type GetPrescriptionByConsultationRow struct {
	ID               int64
	ConsultationID   int64
	PatientProfileID int64
	DoctorProfileID  int64
	IssuedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Xmin             string
}

func (q *Queries) GetPrescriptionByConsultation(ctx context.Context, consultationID int64) (GetPrescriptionByConsultationRow, error) {
	row := q.db.QueryRow(ctx, getPrescriptionByConsultation, consultationID)
	var i GetPrescriptionByConsultationRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xmin,
	)
	return i, err
}

const insertMedication = `-- name: InsertMedication :one
INSERT INTO clinical_prescribed_medications (
    prescription_id, medication_name, dosage, frequency, duration_days, notes
) VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, created_at
`

type InsertMedicationParams struct {
	PrescriptionID int64
	MedicationName string
	Dosage         string
	Frequency      string
	DurationDays   int32
	Notes          *string
}

type InsertMedicationRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertMedication(ctx context.Context, arg InsertMedicationParams) (InsertMedicationRow, error) {
	row := q.db.QueryRow(ctx, insertMedication,
		arg.PrescriptionID,
		arg.MedicationName,
		arg.Dosage,
		arg.Frequency,
		arg.DurationDays,
		arg.Notes,
	)
	var i InsertMedicationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPrescription = `-- name: InsertPrescription :one
INSERT INTO clinical_prescriptions (
    consultation_id, patient_profile_id, doctor_profile_id
) VALUES ($1, $2, $3)
    RETURNING id, issued_at, created_at, updated_at, xmin::text AS xmin
`

type InsertPrescriptionParams struct {
	ConsultationID   int64
	PatientProfileID int64
	DoctorProfileID  int64
}

type InsertPrescriptionRow struct {
	ID        int64
	IssuedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Xmin      string
}

func (q *Queries) InsertPrescription(ctx context.Context, arg InsertPrescriptionParams) (InsertPrescriptionRow, error) {
	row := q.db.QueryRow(ctx, insertPrescription, arg.ConsultationID, arg.PatientProfileID, arg.DoctorProfileID)
	var i InsertPrescriptionRow
	err := row.Scan(
		&i.ID,
		&i.IssuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xmin,
	)
	return i, err
}

const touchPrescription = `-- name: TouchPrescription :exec
UPDATE clinical_prescriptions SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchPrescription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchPrescription, id)
	return err
}
