// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"tibi/internal/queue/queueentry"
)

type ConsultationStatus string

const (
	ConsultationStatusPending    ConsultationStatus = "Pending"
	ConsultationStatusInProgress ConsultationStatus = "InProgress"
	ConsultationStatusConfirmed  ConsultationStatus = "Confirmed"
	ConsultationStatusCompleted  ConsultationStatus = "Completed"
	ConsultationStatusCancelled  ConsultationStatus = "Cancelled"
	ConsultationStatusNoShow     ConsultationStatus = "NoShow"
)

func (e *ConsultationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsultationStatus(s)
	case string:
		*e = ConsultationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsultationStatus: %T", src)
	}
	return nil
}

type NullConsultationStatus struct {
	ConsultationStatus ConsultationStatus
	Valid              bool // Valid is true if ConsultationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsultationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConsultationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsultationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsultationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsultationStatus), nil
}

type FileScope string

const (
	FileScopeProfileImage      FileScope = "ProfileImage"
	FileScopePostAttachment    FileScope = "PostAttachment"
	FileScopeMedicalAttachment FileScope = "MedicalAttachment"
)

func (e *FileScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileScope(s)
	case string:
		*e = FileScope(s)
	default:
		return fmt.Errorf("unsupported scan type for FileScope: %T", src)
	}
	return nil
}

type NullFileScope struct {
	FileScope FileScope
	Valid     bool // Valid is true if FileScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileScope) Scan(value interface{}) error {
	if value == nil {
		ns.FileScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileScope), nil
}

type PaymentChannel string

const (
	PaymentChannelCard         PaymentChannel = "Card"
	PaymentChannelMobileWallet PaymentChannel = "MobileWallet"
	PaymentChannelInstaPay     PaymentChannel = "InstaPay"
)

func (e *PaymentChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentChannel(s)
	case string:
		*e = PaymentChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentChannel: %T", src)
	}
	return nil
}

type NullPaymentChannel struct {
	PaymentChannel PaymentChannel
	Valid          bool // Valid is true if PaymentChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentChannel) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentChannel), nil
}

type PaymentStatus string

const (
	PaymentStatusPending   PaymentStatus = "Pending"
	PaymentStatusSucceeded PaymentStatus = "Succeeded"
	PaymentStatusFailed    PaymentStatus = "Failed"
	PaymentStatusRefunded  PaymentStatus = "Refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PostType string

const (
	PostTypeHealthTip        PostType = "HealthTip"
	PostTypePatientEducation PostType = "PatientEducation"
	PostTypeClinicNews       PostType = "ClinicNews"
	PostTypePublication      PostType = "Publication"
)

func (e *PostType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostType(s)
	case string:
		*e = PostType(s)
	default:
		return fmt.Errorf("unsupported scan type for PostType: %T", src)
	}
	return nil
}

type NullPostType struct {
	PostType PostType
	Valid    bool // Valid is true if PostType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostType) Scan(value interface{}) error {
	if value == nil {
		ns.PostType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostType), nil
}

type QueueSessionStatus string

const (
	QueueSessionStatusScheduled QueueSessionStatus = "Scheduled"
	QueueSessionStatusOpen      QueueSessionStatus = "Open"
	QueueSessionStatusClosed    QueueSessionStatus = "Closed"
	QueueSessionStatusCancelled QueueSessionStatus = "Cancelled"
)

func (e *QueueSessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QueueSessionStatus(s)
	case string:
		*e = QueueSessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QueueSessionStatus: %T", src)
	}
	return nil
}

type NullQueueSessionStatus struct {
	QueueSessionStatus QueueSessionStatus
	Valid              bool // Valid is true if QueueSessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQueueSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QueueSessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QueueSessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQueueSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QueueSessionStatus), nil
}

type QueueStatus string

const (
	QueueStatusWaiting    QueueStatus = "Waiting"
	QueueStatusCalled     QueueStatus = "Called"
	QueueStatusInProgress QueueStatus = "InProgress"
	QueueStatusCompleted  QueueStatus = "Completed"
	QueueStatusSkipped    QueueStatus = "Skipped"
	QueueStatusNoShow     QueueStatus = "NoShow"
	QueueStatusCancelled  QueueStatus = "Cancelled"
)

func (e *QueueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QueueStatus(s)
	case string:
		*e = QueueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QueueStatus: %T", src)
	}
	return nil
}

type NullQueueStatus struct {
	QueueStatus QueueStatus
	Valid       bool // Valid is true if QueueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQueueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QueueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QueueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQueueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QueueStatus), nil
}

type ScheduleExceptionType string

const (
	ScheduleExceptionTypeClosed        ScheduleExceptionType = "Closed"
	ScheduleExceptionTypeOpenEarly     ScheduleExceptionType = "OpenEarly"
	ScheduleExceptionTypeOpenLate      ScheduleExceptionType = "OpenLate"
	ScheduleExceptionTypeModifiedHours ScheduleExceptionType = "ModifiedHours"
)

func (e *ScheduleExceptionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleExceptionType(s)
	case string:
		*e = ScheduleExceptionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleExceptionType: %T", src)
	}
	return nil
}

type NullScheduleExceptionType struct {
	ScheduleExceptionType ScheduleExceptionType
	Valid                 bool // Valid is true if ScheduleExceptionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleExceptionType) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleExceptionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleExceptionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleExceptionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleExceptionType), nil
}

type UserRole string

const (
	UserRolePatient       UserRole = "Patient"
	UserRoleDoctor        UserRole = "Doctor"
	UserRolePendingDoctor UserRole = "PendingDoctor"
	UserRoleAdmin         UserRole = "Admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationStatus string

const (
	VerificationStatusNotSubmitted  VerificationStatus = "NotSubmitted"
	VerificationStatusPendingReview VerificationStatus = "PendingReview"
	VerificationStatusVerified      VerificationStatus = "Verified"
	VerificationStatusRejected      VerificationStatus = "Rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus
	Valid              bool // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type VoteChoice string

const (
	VoteChoiceFor     VoteChoice = "For"
	VoteChoiceAgainst VoteChoice = "Against"
)

func (e *VoteChoice) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoteChoice(s)
	case string:
		*e = VoteChoice(s)
	default:
		return fmt.Errorf("unsupported scan type for VoteChoice: %T", src)
	}
	return nil
}

type NullVoteChoice struct {
	VoteChoice VoteChoice
	Valid      bool // Valid is true if VoteChoice is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoteChoice) Scan(value interface{}) error {
	if value == nil {
		ns.VoteChoice, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoteChoice.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoteChoice) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoteChoice), nil
}

type VoteStatus string

const (
	VoteStatusOpen     VoteStatus = "Open"
	VoteStatusResolved VoteStatus = "Resolved"
	VoteStatusExpired  VoteStatus = "Expired"
)

func (e *VoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoteStatus(s)
	case string:
		*e = VoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VoteStatus: %T", src)
	}
	return nil
}

type NullVoteStatus struct {
	VoteStatus VoteStatus
	Valid      bool // Valid is true if VoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoteStatus), nil
}

type AdminVote struct {
	ID            int64
	ActionType    string
	TargetUserID  int64
	Status        VoteStatus
	RequiredVotes int32
	VotesFor      int32
	VotesAgainst  int32
	ExpiresAt     pgtype.Timestamptz
	ResolvedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Xmin          pgtype.Uint32
}

type AdminVoteParticipant struct {
	ID          int64
	AdminVoteID int64
	AdminUserID int64
	Vote        VoteChoice
	VotedAt     pgtype.Timestamptz
}

type ClinicalMedicalAttachment struct {
	ID              int64
	MedicalRecordID int64
	FileID          int64
	Label           *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ClinicalMedicalRecord struct {
	ID                 int64
	ConsultationID     int64
	PatientProfileID   int64
	DoctorProfileID    int64
	Allergies          *string
	CurrentMedications *string
	PastConditions     *string
	DoctorNotes        *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Xmin               pgtype.Uint32
}

type ClinicalPrescribedMedication struct {
	ID             int64
	PrescriptionID int64
	MedicationName string
	Dosage         string
	Frequency      string
	DurationDays   int32
	Notes          *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type ClinicalPrescription struct {
	ID               int64
	ConsultationID   int64
	PatientProfileID int64
	DoctorProfileID  int64
	IssuedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Xmin             pgtype.Uint32
}

type ConsultationsConsultation struct {
	ID               int64
	PatientProfileID int64
	DoctorProfileID  int64
	ClinicSessionID  *int64
	ScheduledAt      pgtype.Timestamptz
	DurationMinutes  int32
	Status           ConsultationStatus
	IsUrgent         bool
	Notes            *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Xmin             pgtype.Uint32
}

type ContentPost struct {
	ID              int64
	DoctorProfileID int64
	Title           string
	Content         string
	Excerpt         *string
	Type            PostType
	CoverImageUrl   *string
	ViewCount       int32
	LikeCount       int32
	IsPublished     bool
	IsFeatured      bool
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ContentPostAttachment struct {
	ID           int64
	DoctorPostID int64
	FileUrl      *string
	FileType     string
	FileID       *int64
}

type DoctorsClinicSession struct {
	ID              int64
	DoctorProfileID int64
	SessionDate     pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	CreatedAt       pgtype.Timestamptz
}

type DoctorsProfile struct {
	ID                          int64
	UserID                      int64
	FullName                    string
	Bio                         string
	ConsultationFee             pgtype.Numeric
	Currency                    string
	ClinicName                  string
	ClinicAddress               string
	MedicalLicenseNumber        *string
	VerificationStatus          VerificationStatus
	VerificationRejectionReason *string
	SubmittedAt                 pgtype.Timestamptz
	AverageRating               pgtype.Numeric
	RatingCount                 int32
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	Xmin                        pgtype.Uint32
}

type DoctorsProfileSpecialty struct {
	DoctorProfileID int64
	SpecialtyID     int64
}

type DoctorsScheduleException struct {
	ID              int64
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
	FromTime        pgtype.Time
	ToTime          pgtype.Time
	Type            ScheduleExceptionType
	Reason          *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type DoctorsSpecialty struct {
	ID                int64
	Name              string
	ParentSpecialtyID *int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DoctorsWeeklySchedule struct {
	ID                  int64
	DoctorProfileID     int64
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type IdentityRefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type IdentityUser struct {
	ID              int64
	Email           string
	PasswordHash    string
	Role            UserRole
	ProfileImageUrl *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type PatientsProfile struct {
	ID                    int64
	UserID                int64
	FullName              string
	PhoneNumber           string
	DateOfBirth           pgtype.Date
	InsuranceProvider     *string
	InsurancePolicyNumber *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type PaymentsPayment struct {
	ID               int64
	PatientProfileID int64
	DoctorProfileID  int64
	ConsultationID   int64
	Amount           pgtype.Numeric
	Currency         string
	Channel          PaymentChannel
	TransactionID    *string
	Status           PaymentStatus
	TransactionDate  pgtype.Timestamptz
	CheckoutUrl      *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type PlatformFile struct {
	ID            int64
	UploaderID    int64
	Scope         FileScope
	ObjectKey     string
	OriginalName  string
	ContentType   string
	SizeBytes     int64
	ContentSha256 string
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type QueueEntry struct {
	ID               int64
	ConsultationID   int64
	QueueWindowID    int64
	ClinicSessionID  int64
	PatientProfileID int64
	QueueNumber      int32
	IsPriority       bool
	Status           queueentry.Status
	CheckedInAt      pgtype.Timestamptz
	CalledAt         pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	SkipReason       *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Xmin             pgtype.Uint32
}

type QueueWindow struct {
	ID                  int64
	ClinicSessionID     int64
	Status              QueueSessionStatus
	NextQueueNumber     int32
	CurrentQueueEntryID *int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Xmin                pgtype.Uint32
}
