// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"tibi/internal/queue/queueentry"
)

const clearWindowCurrent = `-- name: ClearWindowCurrent :exec
UPDATE queue_windows
SET current_queue_entry_id = NULL, updated_at = $2
WHERE id = $1 AND current_queue_entry_id = $3
`

type ClearWindowCurrentParams struct {
	ID                  int64
	UpdatedAt           pgtype.Timestamptz
	CurrentQueueEntryID *int64
}

func (q *Queries) ClearWindowCurrent(ctx context.Context, arg ClearWindowCurrentParams) error {
	_, err := q.db.Exec(ctx, clearWindowCurrent, arg.ID, arg.UpdatedAt, arg.CurrentQueueEntryID)
	return err
}

const getEntryForUpdate = `-- name: GetEntryForUpdate :one
SELECT queue_entries.id, consultation_id, queue_window_id, clinic_session_id,
       patient_profile_id, queue_number, is_priority, status,
       checked_in_at, called_at, started_at, completed_at, skip_reason,
       created_at, updated_at, queue_entries.xmin::text AS xmin,
       (SELECT p.user_id FROM patients_profiles p WHERE p.id = queue_entries.patient_profile_id) AS patient_user_id
FROM queue_entries
WHERE queue_entries.id = $1
  AND EXISTS (
      SELECT 1 FROM doctors_clinic_sessions s
      JOIN doctors_profiles d ON d.id = s.doctor_profile_id
      WHERE s.id = queue_entries.clinic_session_id
        AND (
            d.user_id = $2
            OR EXISTS (
                SELECT 1 FROM identity_users u
                WHERE u.id = $2 AND u.role = 'Admin' AND u.deleted_at IS NULL
            )
        )
  )
FOR UPDATE
`

type GetEntryForUpdateParams struct {
	ID     int64
	UserID int64
}

type GetEntryForUpdateRow struct {
	ID               int64
	ConsultationID   int64
	QueueWindowID    int64
	ClinicSessionID  int64
	PatientProfileID int64
	QueueNumber      int32
	IsPriority       bool
	Status           queueentry.Status
	CheckedInAt      pgtype.Timestamptz
	CalledAt         pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	SkipReason       *string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Xmin             string
	PatientUserID    int64
}

func (q *Queries) GetEntryForUpdate(ctx context.Context, arg GetEntryForUpdateParams) (GetEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getEntryForUpdate, arg.ID, arg.UserID)
	var i GetEntryForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.QueueWindowID,
		&i.ClinicSessionID,
		&i.PatientProfileID,
		&i.QueueNumber,
		&i.IsPriority,
		&i.Status,
		&i.CheckedInAt,
		&i.CalledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xmin,
		&i.PatientUserID,
	)
	return i, err
}

const hasOtherActive = `-- name: HasOtherActive :one
SELECT EXISTS (
    SELECT 1 FROM queue_entries
    WHERE queue_window_id = $1
      AND status IN ('Called', 'InProgress')
      AND id != $2
) AS has_other
`

type HasOtherActiveParams struct {
	QueueWindowID int64
	ID            int64
}

func (q *Queries) HasOtherActive(ctx context.Context, arg HasOtherActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOtherActive, arg.QueueWindowID, arg.ID)
	var has_other bool
	err := row.Scan(&has_other)
	return has_other, err
}

const setWindowCurrent = `-- name: SetWindowCurrent :exec
UPDATE queue_windows
SET current_queue_entry_id = $2, updated_at = $3
WHERE id = $1
`

type SetWindowCurrentParams struct {
	ID                  int64
	CurrentQueueEntryID *int64
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) SetWindowCurrent(ctx context.Context, arg SetWindowCurrentParams) error {
	_, err := q.db.Exec(ctx, setWindowCurrent, arg.ID, arg.CurrentQueueEntryID, arg.UpdatedAt)
	return err
}

const updateEntryStatus = `-- name: UpdateEntryStatus :execrows
UPDATE queue_entries
SET status = $2, called_at = $3, started_at = $4,
    completed_at = $5, skip_reason = $6, updated_at = $7
WHERE id = $1 AND xmin::text = $8::text
`

type UpdateEntryStatusParams struct {
	ID          int64
	Status      queueentry.Status
	CalledAt    pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	SkipReason  *string
	UpdatedAt   pgtype.Timestamptz
	Xmin        string
}

func (q *Queries) UpdateEntryStatus(ctx context.Context, arg UpdateEntryStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEntryStatus,
		arg.ID,
		arg.Status,
		arg.CalledAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.SkipReason,
		arg.UpdatedAt,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
