// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getForCancel = `-- name: GetForCancel :one
SELECT c.id, c.status, c.scheduled_at, pp.user_id AS patient_user_id,
       dp.user_id AS doctor_user_id, c.xmin::text AS xmin
FROM consultations_consultations c
JOIN patients_profiles pp ON pp.id = c.patient_profile_id
JOIN doctors_profiles dp ON dp.id = c.doctor_profile_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetForCancelRow struct {
	ID            int64
	Status        ConsultationStatus
	ScheduledAt   pgtype.Timestamptz
	PatientUserID int64
	DoctorUserID  int64
	Xmin          string
}

func (q *Queries) GetForCancel(ctx context.Context, id int64) (GetForCancelRow, error) {
	row := q.db.QueryRow(ctx, getForCancel, id)
	var i GetForCancelRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ScheduledAt,
		&i.PatientUserID,
		&i.DoctorUserID,
		&i.Xmin,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :execrows
UPDATE consultations_consultations
SET status = $2, updated_at = $3
WHERE id = $1 AND xmin::text = $4 AND deleted_at IS NULL
`

type UpdateStatusParams struct {
	ID        int64
	Status    ConsultationStatus
	UpdatedAt pgtype.Timestamptz
	Xmin      pgtype.Uint32
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
