// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blocksInRange = `-- name: BlocksInRange :many
SELECT day_of_week, start_time, end_time, slot_duration_minutes, is_active
FROM doctors_weekly_schedules
WHERE doctor_profile_id = $1 AND is_active
`

type BlocksInRangeRow struct {
	DayOfWeek           int16
	StartTime           pgtype.Time
	EndTime             pgtype.Time
	SlotDurationMinutes int32
	IsActive            bool
}

func (q *Queries) BlocksInRange(ctx context.Context, doctorProfileID int64) ([]BlocksInRangeRow, error) {
	rows, err := q.db.Query(ctx, blocksInRange, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlocksInRangeRow
	for rows.Next() {
		var i BlocksInRangeRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.SlotDurationMinutes,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookedInRange = `-- name: BookedInRange :many
SELECT scheduled_at
FROM consultations_consultations
WHERE doctor_profile_id = $1
  AND scheduled_at >= $2 AND scheduled_at < $3
  AND deleted_at IS NULL
  AND (
    status IN ('Confirmed', 'InProgress')
    OR (status = 'Pending' AND created_at > now() - INTERVAL '15 minutes')
  )
`

type BookedInRangeParams struct {
	DoctorProfileID int64
	ScheduledAt     pgtype.Timestamptz
	ScheduledAt_2   pgtype.Timestamptz
}

func (q *Queries) BookedInRange(ctx context.Context, arg BookedInRangeParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, bookedInRange, arg.DoctorProfileID, arg.ScheduledAt, arg.ScheduledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var scheduled_at pgtype.Timestamptz
		if err := rows.Scan(&scheduled_at); err != nil {
			return nil, err
		}
		items = append(items, scheduled_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exceptionsInRange = `-- name: ExceptionsInRange :many
SELECT exception_date, from_time, to_time, type
FROM doctors_schedule_exceptions
WHERE doctor_profile_id = $1
  AND exception_date BETWEEN $2 AND $3
  AND type = 'Closed'
`

type ExceptionsInRangeParams struct {
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
	ExceptionDate_2 pgtype.Date
}

type ExceptionsInRangeRow struct {
	ExceptionDate pgtype.Date
	FromTime      pgtype.Time
	ToTime        pgtype.Time
	Type          ScheduleExceptionType
}

func (q *Queries) ExceptionsInRange(ctx context.Context, arg ExceptionsInRangeParams) ([]ExceptionsInRangeRow, error) {
	rows, err := q.db.Query(ctx, exceptionsInRange, arg.DoctorProfileID, arg.ExceptionDate, arg.ExceptionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExceptionsInRangeRow
	for rows.Next() {
		var i ExceptionsInRangeRow
		if err := rows.Scan(
			&i.ExceptionDate,
			&i.FromTime,
			&i.ToTime,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerifiedDoctor = `-- name: GetVerifiedDoctor :one
SELECT id FROM doctors_profiles
WHERE id = $1 AND verification_status = 'Verified' AND deleted_at IS NULL
`

func (q *Queries) GetVerifiedDoctor(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getVerifiedDoctor, id)
	err := row.Scan(&id)
	return id, err
}
