// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDoctorProfileID = `-- name: GetDoctorProfileID :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorProfileID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertException = `-- name: InsertException :one
INSERT INTO doctors_schedule_exceptions (
    doctor_profile_id, exception_date, from_time, to_time, type, reason
) VALUES ($1, $2, $3::time, $4::time, $5, $6)
RETURNING id
`

type InsertExceptionParams struct {
	DoctorProfileID int64
	ExceptionDate   pgtype.Date
	Column3         pgtype.Time
	Column4         pgtype.Time
	Type            ScheduleExceptionType
	Reason          pgtype.Text
}

func (q *Queries) InsertException(ctx context.Context, arg InsertExceptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertException,
		arg.DoctorProfileID,
		arg.ExceptionDate,
		arg.Column3,
		arg.Column4,
		arg.Type,
		arg.Reason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
