// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const insertPatientProfile = `-- name: InsertPatientProfile :one
INSERT INTO patients_profiles (user_id, full_name, phone_number)
VALUES ($1, $2, $3)
    RETURNING id
`

type InsertPatientProfileParams struct {
	UserID      int64
	FullName    string
	PhoneNumber string
}

func (q *Queries) InsertPatientProfile(ctx context.Context, arg InsertPatientProfileParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPatientProfile, arg.UserID, arg.FullName, arg.PhoneNumber)
	var id int64
	err := row.Scan(&id)
	return id, err
}
