// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSuspension = `-- name: InsertSuspension :one
INSERT INTO admin_user_suspensions (
    user_id, reason, from_ts, to_ts, vote_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertSuspensionParams struct {
	UserID int64
	Reason string
	FromTs pgtype.Timestamptz
	ToTs   pgtype.Timestamptz
	VoteID *int64
}

type InsertSuspensionRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertSuspension(ctx context.Context, arg InsertSuspensionParams) (InsertSuspensionRow, error) {
	row := q.db.QueryRow(ctx, insertSuspension,
		arg.UserID,
		arg.Reason,
		arg.FromTs,
		arg.ToTs,
		arg.VoteID,
	)
	var i InsertSuspensionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE identity_refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}
