// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerification = `-- name: ConsumeVerification :execrows
UPDATE identity_email_verifications
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND xmin::text = $2
`

type ConsumeVerificationParams struct {
	ID   int64
	Xmin pgtype.Uint32
}

func (q *Queries) ConsumeVerification(ctx context.Context, arg ConsumeVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerification, arg.ID, arg.Xmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVerificationForUpdate = `-- name: GetVerificationForUpdate :one
SELECT id, user_id, expires_at, consumed_at,
       xmin::text AS xmin
FROM identity_email_verifications
WHERE token_hash = $1
FOR UPDATE
`

type GetVerificationForUpdateRow struct {
	ID         int64
	UserID     int64
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	Xmin       string
}

func (q *Queries) GetVerificationForUpdate(ctx context.Context, tokenHash string) (GetVerificationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getVerificationForUpdate, tokenHash)
	var i GetVerificationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Xmin,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE identity_users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL AND email_verified_at IS NULL
`

func (q *Queries) SetEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}
