// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNotification = `-- name: InsertNotification :one
INSERT INTO communication_notifications (
    user_id, type, title, body, payload
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertNotificationParams struct {
	UserID  int64
	Type    string
	Title   string
	Body    string
	Payload []byte
}

type InsertNotificationRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (InsertNotificationRow, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	var i InsertNotificationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
