// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecordForRead = `-- name: GetRecordForRead :one
SELECT r.id, r.consultation_id, r.patient_profile_id, r.doctor_profile_id,
       r.allergies, r.current_medications, r.past_conditions, r.doctor_notes,
       r.created_at, r.updated_at
FROM clinical_medical_records r
         JOIN consultations_consultations c ON c.id = r.consultation_id
         LEFT JOIN patients_profiles p ON p.id = c.patient_profile_id AND p.user_id = $2
         LEFT JOIN doctors_profiles  d ON d.id = c.doctor_profile_id  AND d.user_id = $2
WHERE r.consultation_id = $1
  AND r.deleted_at IS NULL
  AND (p.id IS NOT NULL OR d.id IS NOT NULL)
`

type GetRecordForReadParams struct {
	ConsultationID int64
	UserID         int64
}

type GetRecordForReadRow struct {
	ID                 int64
	ConsultationID     int64
	PatientProfileID   int64
	DoctorProfileID    int64
	Allergies          *string
	CurrentMedications *string
	PastConditions     *string
	DoctorNotes        *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetRecordForRead(ctx context.Context, arg GetRecordForReadParams) (GetRecordForReadRow, error) {
	row := q.db.QueryRow(ctx, getRecordForRead, arg.ConsultationID, arg.UserID)
	var i GetRecordForReadRow
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.Allergies,
		&i.CurrentMedications,
		&i.PastConditions,
		&i.DoctorNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, file_id, label, created_at
FROM clinical_medical_attachments
WHERE medical_record_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListAttachmentsRow struct {
	ID        int64
	FileID    int64
	Label     *string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAttachments(ctx context.Context, medicalRecordID int64) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, medicalRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
