// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const profileID = `-- name: ProfileID :one
SELECT id FROM doctors_profiles WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ProfileID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, profileID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const softDelete = `-- name: SoftDelete :execrows
UPDATE content_posts
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND doctor_profile_id = $2 AND deleted_at IS NULL
`

type SoftDeleteParams struct {
	ID              int64
	DoctorProfileID int64
}

func (q *Queries) SoftDelete(ctx context.Context, arg SoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDelete, arg.ID, arg.DoctorProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
