// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAndCountView = `-- name: GetAndCountView :one
WITH updated AS (
    UPDATE content_posts
    SET view_count = view_count + 1
    WHERE id = $1::bigint
      AND is_published
      AND deleted_at IS NULL
    RETURNING id, title, content, COALESCE(excerpt, '') AS excerpt, type, cover_image_url,
              view_count, like_count, COALESCE(published_at, created_at) AS published_at, doctor_profile_id
)
SELECT
    up.id, up.title, up.content, up.excerpt, up.type, up.cover_image_url,
    up.view_count, up.like_count, up.published_at,
    d.id AS doctor_id, d.full_name AS doctor_full_name,
    u.profile_image_url AS doctor_profile_image_url
FROM updated up
JOIN doctors_profiles d ON d.id = up.doctor_profile_id AND d.deleted_at IS NULL
JOIN identity_users  u ON u.id = d.user_id AND u.deleted_at IS NULL
`

type GetAndCountViewRow struct {
	ID                    int64
	Title                 string
	Content               string
	Excerpt               string
	Type                  PostType
	CoverImageUrl         pgtype.Text
	ViewCount             int32
	LikeCount             int32
	PublishedAt           pgtype.Timestamptz
	DoctorID              int64
	DoctorFullName        string
	DoctorProfileImageUrl pgtype.Text
}

func (q *Queries) GetAndCountView(ctx context.Context, id int64) (GetAndCountViewRow, error) {
	row := q.db.QueryRow(ctx, getAndCountView, id)
	var i GetAndCountViewRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Excerpt,
		&i.Type,
		&i.CoverImageUrl,
		&i.ViewCount,
		&i.LikeCount,
		&i.PublishedAt,
		&i.DoctorID,
		&i.DoctorFullName,
		&i.DoctorProfileImageUrl,
	)
	return i, err
}

const specialties = `-- name: Specialties :many
SELECT s.name
FROM doctors_profile_specialties dps
JOIN doctors_specialties s ON s.id = dps.specialty_id
WHERE dps.doctor_profile_id = $1
ORDER BY s.name
`

func (q *Queries) Specialties(ctx context.Context, doctorProfileID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, specialties, doctorProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
