// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInbox = `-- name: CountInbox :one
SELECT COUNT(*)::bigint
FROM doctorposts_free_messages
WHERE doctor_profile_id = $1
  AND ($2::boolean IS NULL
       OR $2::boolean = false
       OR is_replied_to = false)
`

type CountInboxParams struct {
	DoctorProfileID int64
	UnrepliedOnly   *bool
}

func (q *Queries) CountInbox(ctx context.Context, arg CountInboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInbox, arg.DoctorProfileID, arg.UnrepliedOnly)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getDoctorProfileIDForUser = `-- name: GetDoctorProfileIDForUser :one
SELECT id FROM doctors_profiles
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDoctorProfileIDForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDoctorProfileIDForUser, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listInbox = `-- name: ListInbox :many
SELECT id, sender_name, sender_email, sender_phone, content,
       is_replied_to, replied_at, reply_content, created_at
FROM doctorposts_free_messages
WHERE doctor_profile_id = $1
  AND ($4::boolean IS NULL
       OR $4::boolean = false
       OR is_replied_to = false)
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListInboxParams struct {
	DoctorProfileID int64
	Limit           int32
	Offset          int32
	UnrepliedOnly   *bool
}

type ListInboxRow struct {
	ID           int64
	SenderName   string
	SenderEmail  string
	SenderPhone  *string
	Content      string
	IsRepliedTo  bool
	RepliedAt    pgtype.Timestamptz
	ReplyContent *string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.DoctorProfileID,
		arg.Limit,
		arg.Offset,
		arg.UnrepliedOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxRow
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderPhone,
			&i.Content,
			&i.IsRepliedTo,
			&i.RepliedAt,
			&i.ReplyContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
