// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :execrows
UPDATE identity_password_resets
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND xmin::text = $2
`

type ConsumePasswordResetParams struct {
	ID   int64
	Xmin pgtype.Uint32
}

func (q *Queries) ConsumePasswordReset(ctx context.Context, arg ConsumePasswordResetParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordReset, arg.ID, arg.Xmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordResetForUpdate = `-- name: GetPasswordResetForUpdate :one
SELECT id, user_id, expires_at, consumed_at,
       xmin::text AS xmin
FROM identity_password_resets
WHERE token_hash = $1
FOR UPDATE
`

type GetPasswordResetForUpdateRow struct {
	ID         int64
	UserID     int64
	ExpiresAt  pgtype.Timestamptz
	ConsumedAt pgtype.Timestamptz
	Xmin       string
}

func (q *Queries) GetPasswordResetForUpdate(ctx context.Context, tokenHash string) (GetPasswordResetForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetForUpdate, tokenHash)
	var i GetPasswordResetForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Xmin,
	)
	return i, err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE identity_refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE identity_users
SET password_hash = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
