// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsultationParticipants = `-- name: GetConsultationParticipants :one
SELECT
    c.id,
    c.patient_profile_id,
    c.doctor_profile_id,
    p.user_id AS patient_user_id,
    d.user_id AS doctor_user_id,
    c.status
FROM consultations_consultations c
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles  d ON d.id = c.doctor_profile_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetConsultationParticipantsRow struct {
	ID               int64
	PatientProfileID int64
	DoctorProfileID  int64
	PatientUserID    int64
	DoctorUserID     int64
	Status           ConsultationStatus
}

func (q *Queries) GetConsultationParticipants(ctx context.Context, id int64) (GetConsultationParticipantsRow, error) {
	row := q.db.QueryRow(ctx, getConsultationParticipants, id)
	var i GetConsultationParticipantsRow
	err := row.Scan(
		&i.ID,
		&i.PatientProfileID,
		&i.DoctorProfileID,
		&i.PatientUserID,
		&i.DoctorUserID,
		&i.Status,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO communication_messages (
    consultation_id, sender_user_id, content, sent_at
) VALUES ($1, $2, $3, $4)
RETURNING id, sent_at, created_at
`

type InsertMessageParams struct {
	ConsultationID int64
	SenderUserID   int64
	Content        string
	SentAt         pgtype.Timestamptz
}

type InsertMessageRow struct {
	ID        int64
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConsultationID,
		arg.SenderUserID,
		arg.Content,
		arg.SentAt,
	)
	var i InsertMessageRow
	err := row.Scan(&i.ID, &i.SentAt, &i.CreatedAt)
	return i, err
}
