// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getFileByID = `-- name: GetFileByID :one
SELECT id, uploader_id, scope, object_key, original_name,
       content_type, size_bytes, content_sha256, created_at, deleted_at
FROM platform_files
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (PlatformFile, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i PlatformFile
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.Scope,
		&i.ObjectKey,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.ContentSha256,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
