// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsultationForComplete = `-- name: GetConsultationForComplete :one
SELECT id, status, updated_at, xmin::text AS xmin
FROM consultations_consultations
WHERE id = $1 AND deleted_at IS NULL
`

type GetConsultationForCompleteRow struct {
	ID        int64
	Status    ConsultationStatus
	UpdatedAt pgtype.Timestamptz
	Xmin      string
}

func (q *Queries) GetConsultationForComplete(ctx context.Context, id int64) (GetConsultationForCompleteRow, error) {
	row := q.db.QueryRow(ctx, getConsultationForComplete, id)
	var i GetConsultationForCompleteRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.UpdatedAt,
		&i.Xmin,
	)
	return i, err
}

const updateConsultationCompleted = `-- name: UpdateConsultationCompleted :execrows
UPDATE consultations_consultations
SET status = 'Completed', updated_at = $2
WHERE id = $1 AND xmin::text = $3::text
`

type UpdateConsultationCompletedParams struct {
	ID        int64
	UpdatedAt pgtype.Timestamptz
	Xmin      string
}

func (q *Queries) UpdateConsultationCompleted(ctx context.Context, arg UpdateConsultationCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConsultationCompleted, arg.ID, arg.UpdatedAt, arg.Xmin)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
