// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsultationForConfirm = `-- name: GetConsultationForConfirm :one
SELECT c.id, c.status, c.created_at, c.updated_at, c.xmin::text AS xmin,
       p.user_id AS patient_user_id, d.user_id AS doctor_user_id
FROM consultations_consultations c
JOIN patients_profiles p ON p.id = c.patient_profile_id
JOIN doctors_profiles d ON d.id = c.doctor_profile_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetConsultationForConfirmRow struct {
	ID            int64
	Status        ConsultationStatus
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Xmin          string
	PatientUserID int64
	DoctorUserID  int64
}

// Cross-module read: patients_profiles and doctors_profiles for WS notify (R2).
func (q *Queries) GetConsultationForConfirm(ctx context.Context, id int64) (GetConsultationForConfirmRow, error) {
	row := q.db.QueryRow(ctx, getConsultationForConfirm, id)
	var i GetConsultationForConfirmRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Xmin,
		&i.PatientUserID,
		&i.DoctorUserID,
	)
	return i, err
}

const updateConsultationStatus = `-- name: UpdateConsultationStatus :execrows
UPDATE consultations_consultations
SET status = $2, updated_at = $3
WHERE id = $1 AND xmin::text = $4::text
`

type UpdateConsultationStatusParams struct {
	ID        int64
	Status    ConsultationStatus
	UpdatedAt pgtype.Timestamptz
	Xmin      string
}

func (q *Queries) UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConsultationStatus,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
