// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const cancelQueueEntryByConsultation = `-- name: CancelQueueEntryByConsultation :execrows
UPDATE queue_entries
SET status = 'Cancelled', updated_at = now()
WHERE consultation_id = $1
  AND status IN ('Waiting', 'Called', 'Skipped')
`

func (q *Queries) CancelQueueEntryByConsultation(ctx context.Context, consultationID int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelQueueEntryByConsultation, consultationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionForCancelledEntry = `-- name: GetSessionForCancelledEntry :one
SELECT qe.clinic_session_id,
       p.user_id AS patient_user_id
FROM queue_entries qe
JOIN patients_profiles p ON p.id = qe.patient_profile_id
WHERE qe.consultation_id = $1
LIMIT 1
`

type GetSessionForCancelledEntryRow struct {
	ClinicSessionID int64
	PatientUserID   int64
}

// Cross-module read: patients_profiles for the patient user channel (R2).
func (q *Queries) GetSessionForCancelledEntry(ctx context.Context, consultationID int64) (GetSessionForCancelledEntryRow, error) {
	row := q.db.QueryRow(ctx, getSessionForCancelledEntry, consultationID)
	var i GetSessionForCancelledEntryRow
	err := row.Scan(&i.ClinicSessionID, &i.PatientUserID)
	return i, err
}
