// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSuspensionForUpdate = `-- name: GetSuspensionForUpdate :one
SELECT id, user_id, reason, from_ts, to_ts, lifted_at,
       xmin::text AS xmin
FROM admin_user_suspensions
WHERE id = $1
FOR UPDATE
`

type GetSuspensionForUpdateRow struct {
	ID       int64
	UserID   int64
	Reason   string
	FromTs   pgtype.Timestamptz
	ToTs     pgtype.Timestamptz
	LiftedAt pgtype.Timestamptz
	Xmin     string
}

func (q *Queries) GetSuspensionForUpdate(ctx context.Context, id int64) (GetSuspensionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getSuspensionForUpdate, id)
	var i GetSuspensionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Reason,
		&i.FromTs,
		&i.ToTs,
		&i.LiftedAt,
		&i.Xmin,
	)
	return i, err
}

const liftSuspension = `-- name: LiftSuspension :execrows
UPDATE admin_user_suspensions
SET lifted_at = $2, lifted_by = $3, lift_reason = $4, updated_at = $2
WHERE id = $1 AND xmin::text = $5 AND lifted_at IS NULL
`

type LiftSuspensionParams struct {
	ID         int64
	LiftedAt   pgtype.Timestamptz
	LiftedBy   *int64
	LiftReason *string
	Xmin       pgtype.Uint32
}

func (q *Queries) LiftSuspension(ctx context.Context, arg LiftSuspensionParams) (int64, error) {
	result, err := q.db.Exec(ctx, liftSuspension,
		arg.ID,
		arg.LiftedAt,
		arg.LiftedBy,
		arg.LiftReason,
		arg.Xmin,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
